"""
quench_sweep.py
=================
For each location on the coil, finds the current at which that
location's actual transport current would exceed its local critical
current Ic(B, theta) -- using B interpolated LINEARLY between several
actual FEM solves (from solve_sweep.py's sweep_currents), never
extrapolated beyond them, and the Ic(B, theta) model's own linear,
hard-clamped interpolation (see physics/ic_model.py) so the reported
critical current can never exceed what the manufacturer's table
actually shows.

Why several real solves instead of one solve + analytic scaling:
this magnetostatics problem (mu0 everywhere, no magnetic materials) is
in fact exactly linear in the current, so one solve plus scaling would
give the identical answer up to FEM/solver tolerance. But solving
independently at each current in params.sweep_currents avoids relying
on that argument at all, and is what was asked for -- each
sweep/field_sweep/I_*.npz is a genuine, separate FEM solve, not a
rescaled copy.

The angle to the tape's out-of-plane vector is recomputed from each
solve's own B vector (not assumed constant), then also linearly
interpolated across the solved currents along with |B| -- so both
inputs to the Ic model come from the same real-data interpolation.

Outputs (data in sweep/, plots in visualization/):
  - sweep/quench_results.csv     : per-location data
  - sweep/quench_summary.txt     : weakest point, distribution stats
  - visualization/ic_landscape.png    : where the coil's operating
                                          points sit on the Ic(B,theta)
                                          surface

  quench_3d.png and quench_2d.png are generated by plot_3d.py (run
  separately after this script, using sweep/quench_results.csv).

Run after solve_sweep.py (or after make_test_data.py for a synthetic
test of this script alone):
    python3 quench_sweep.py
"""
import glob

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd

import sys, os
_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
for _p in (_ROOT, os.path.join(_ROOT, "physics"), os.path.join(_ROOT, "mesh"),
           os.path.join(_ROOT, "solve")):
    if _p not in sys.path:
        sys.path.insert(0, _p)

import params
from current_source import (arc_length_xy, normal_xy, turn_index_xy,
                             turn_index_xy_multilayer, layer_index_from_z,
                             expand_to_full_domain)
from ic_model import IcModel, angle_with_normal_deg


def load_field_sweep():
    """
    Loads every sweep/field_sweep/I_*.npz, sorts by the actual solved
    current (read from inside each file, not parsed from the filename),
    and stacks into per-cell arrays across currents. Asserts every file
    shares identical coil cell centroids (true as long as they all came
    from the same mesh, i.e. the same solve_sweep.py run).
    """
    paths = sorted(glob.glob(os.path.join(params.FIELD_SWEEP_DIR, "I_*.npz")))
    if len(paths) < 2:
        raise RuntimeError(
            f"Found {len(paths)} file(s) in {params.FIELD_SWEEP_DIR} -- need at "
            "least 2 different currents to interpolate. Run solve_sweep.py "
            "(or make_test_data.py for a synthetic test) first.")

    datasets = [np.load(p) for p in paths]
    order = np.argsort([float(d["I_solved"]) for d in datasets])
    datasets = [datasets[i] for i in order]

    I_solved = np.array([float(d["I_solved"]) for d in datasets])
    centroids0 = datasets[0]["coil_centroids"]
    for d in datasets[1:]:
        if d["coil_centroids"].shape != centroids0.shape or \
           not np.allclose(d["coil_centroids"], centroids0):
            raise RuntimeError(
                "coil_centroids differ between field_sweep files -- they must "
                "all come from the same mesh (the same solve_sweep.py run). "
                "Delete sweep/field_sweep/ and rerun solve_sweep.py.")

    B_all = np.stack([d["coil_B"] for d in datasets], axis=0)  # (K, N, 3)
    a, b, t, w = (float(datasets[0][k]) for k in ("a", "b", "t", "w"))

    Bmag_all_flat = np.linalg.norm(B_all, axis=2)
    Bmag_max = Bmag_all_flat.max()
    if Bmag_max > 50.0:
        p99 = np.percentile(Bmag_all_flat, 99)
        outlier_ratio = Bmag_max / p99 if p99 > 0 else float("inf")
        if outlier_ratio > 20.0:
            print(f"\n*** WARNING: max |B| across field_sweep/ is {Bmag_max:.3g} T, "
                  f"but the 99th percentile is only {p99:.3g} T (ratio {outlier_ratio:.0f}x) "
                  "-- this is an ISOLATED outlier, not a generally-too-high field. "
                  "That specific pattern (near-correct field almost everywhere plus "
                  "one wild spike) is the signature of gauge/null-space pollution "
                  "leaking through curl(A)'s floating-point cancellation, most "
                  "likely because params.gauge_regularization is too weak for this "
                  "mesh -- check solve/diagnostics.py's outlier_ratio/||A|| fields "
                  "in sweep/solve_sweep_log.txt, try raising gauge_regularization "
                  "by a few orders of magnitude, and rerun solve_sweep.py before "
                  "trusting anything downstream of this. ***\n")
        else:
            print(f"\n*** WARNING: max |B| across field_sweep/ is {Bmag_max:.3g} T "
                  f"(99th percentile {p99:.3g} T -- broadly, not just one cell, too "
                  "high). No real magnet design in this size range produces fields "
                  "that large -- this is the signature of an upstream FEM solve "
                  "that did not actually converge (check solve_sweep.py's printed "
                  "'KSP converged reason' for each current; negative means "
                  "diverged). Re-run solve_sweep.py and look for that before "
                  "trusting anything downstream of this. ***\n")

    return I_solved, centroids0, B_all, a, b, t, w


def interpolate_B_and_angle(I_solved, centroids, B_all, a, b):
    """
    Builds a fine current grid spanning [I_solved.min(), I_solved.max()]
    (params.quench_search_steps_per_interval steps between each pair of
    consecutive solved currents), and linearly interpolates |B| and the
    angle to the tape's out-of-plane vector onto it for every coil cell.
    Both quantities come from the real per-current solves -- nothing is
    assumed about how B scales with current.

    Returns I_fine (M,), Bmag_fine (M, N), theta_fine (M, N).
    """
    from scipy.interpolate import interp1d

    L = b - a
    nx, ny = normal_xy(centroids[:, 0], centroids[:, 1], L)
    n_hat = np.column_stack([nx, ny, np.zeros_like(nx)])  # (N, 3)

    K, N, _ = B_all.shape
    Bmag_all = np.linalg.norm(B_all, axis=2)              # (K, N)
    theta_all = np.stack([angle_with_normal_deg(B_all[k], n_hat)
                           for k in range(K)], axis=0)     # (K, N)

    segs = [np.linspace(I_solved[i], I_solved[i + 1],
                         params.quench_search_steps_per_interval,
                         endpoint=(i == len(I_solved) - 2))
            for i in range(len(I_solved) - 1)]
    I_fine = np.concatenate(segs)

    Bmag_interp = interp1d(I_solved, Bmag_all, axis=0, kind="linear",
                            bounds_error=False, fill_value=np.nan)
    theta_interp = interp1d(I_solved, theta_all, axis=0, kind="linear",
                             bounds_error=False, fill_value=np.nan)
    return I_fine, Bmag_interp(I_fine), theta_interp(I_fine), n_hat


def compute_quench_currents(I_fine, Bmag_fine, theta_fine, model):
    """
    Same brute-force-sweep-plus-linear-refinement logic as before, but
    operating on the (I_fine, Bmag_fine, theta_fine) built from real
    multi-solve interpolation, restricted to the actually-solved current
    range -- no extrapolation beyond it (status "never_quenched" /
    "quenched_at_min" cover the two ways a location can fall outside
    that range, same as before).
    """
    M, N = Bmag_fine.shape
    Ic_fine, frac_clipped = model.critical_current(Bmag_fine.ravel(),
                                                     theta_fine.ravel())
    Ic_fine = Ic_fine.reshape(M, N)

    quenched = I_fine[:, None] > Ic_fine
    any_quench = quenched.any(axis=0)
    first_idx = np.argmax(quenched, axis=0)

    quench_current = np.full(N, np.nan)
    status = np.full(N, "ok", dtype=object)
    status[~any_quench] = "never_quenched"

    at_min = any_quench & (first_idx == 0)
    quench_current[at_min] = I_fine[0]
    status[at_min] = "quenched_at_min"

    refine = any_quench & (first_idx > 0)
    idx = first_idx[refine]
    I_lo, I_hi = I_fine[idx - 1], I_fine[idx]
    f_lo = I_lo - Ic_fine[idx - 1, refine]
    f_hi = I_hi - Ic_fine[idx, refine]
    denom = np.where(f_hi - f_lo == 0, 1.0, f_hi - f_lo)
    frac = np.clip(-f_lo / denom, 0.0, 1.0)
    quench_current[refine] = I_lo + frac * (I_hi - I_lo)

    return quench_current, status, frac_clipped


def build_dataframe(model):
    I_solved, centroids, B_all, a, b, t, w = load_field_sweep()

    # ── Two-coil / symmetry expansion ────────────────────────────────
    eighth = getattr(params, 'use_eighth_symmetry', False)
    if eighth:
        g = getattr(params, 'coil_half_gap', 0.0)
        n_before = len(centroids)
        B_all_exp = np.empty((len(I_solved), 8 * n_before, 3))
        exp_c = None
        for k in range(len(I_solved)):
            exp_c, B_all_exp[k] = expand_to_full_domain(centroids, B_all[k], g)
        centroids = exp_c
        B_all = B_all_exp
        print(f'  8-fold symmetry: {n_before} → {len(centroids)} cells')
    elif getattr(params, 'two_coil_mode', False):
        from coil2_field import superpose_coil2
        print(f'  Two-coil superposition')
        B_all = superpose_coil2(B_all, I_solved, centroids)

    I_fine, Bmag_fine, theta_fine, n_hat = interpolate_B_and_angle(
        I_solved, centroids, B_all, a, b)
    quench_current, status, frac_clipped = compute_quench_currents(
        I_fine, Bmag_fine, theta_fine, model)

    L = b - a
    s = arc_length_xy(centroids[:, 0], centroids[:, 1], L, a)
    # Approximate per-turn bucketing of the homogenized solution -- see
    # the multi-turn modeling note in params.py. This is post-hoc
    # binning of a smooth field by radial position, NOT literally-
    # resolved per-turn data.
    if params.n_layers > 1:
        layer_idx, turn_idx = turn_index_xy_multilayer(
            centroids[:, 0], centroids[:, 1], centroids[:, 2], L)
    else:
        layer_idx = np.zeros(len(centroids), dtype=int)
        turn_idx = turn_index_xy(centroids[:, 0], centroids[:, 1],
                                  L, a, t, params.n_turns_total)
    # report B/theta at the highest solved current actually used, as a
    # representative "design point" value for each location
    Bmag_at_top = np.linalg.norm(B_all[-1], axis=1)
    theta_at_top = angle_with_normal_deg(B_all[-1], n_hat)

    df = pd.DataFrame({
        "x": centroids[:, 0], "y": centroids[:, 1], "z": centroids[:, 2],
        "s": s, "layer_index": layer_idx, "turn_index": turn_idx,
        f"B_at_{I_solved[-1]:.0f}A_T": Bmag_at_top,
        f"angle_at_{I_solved[-1]:.0f}A_deg": theta_at_top,
        "quench_current_A": quench_current,
        "status": status,
    })
    extra = dict(I_solved=I_solved, centroids=centroids, B_all=B_all,
                 a=a, b=b, t=t, w=w, I_fine=I_fine, Bmag_fine=Bmag_fine,
                 theta_fine=theta_fine)
    return df, extra, frac_clipped


def plot_ic_landscape(df, extra, model):
    B_grid = np.linspace(0, model.B_max, 200)
    theta_grid = np.linspace(0, 180, 200)
    Bg, Tg = np.meshgrid(B_grid, theta_grid)
    Ic_grid, _ = model.critical_current(Bg.ravel(), Tg.ravel(), clip_B=False)
    Ic_grid = Ic_grid.reshape(Bg.shape)

    fig, ax = plt.subplots(figsize=(9, 5.5))
    cf = ax.pcolormesh(Bg, Tg, Ic_grid, shading="auto", cmap="viridis")
    cbar = fig.colorbar(cf, ax=ax)
    cbar.set_label("Ic (A)")

    b_col = [c for c in df.columns if c.startswith("B_at_")][0]
    a_col = [c for c in df.columns if c.startswith("angle_at_")][0]
    label_I = b_col.replace("B_at_", "").replace("_T", "")
    ax.scatter(df[b_col], df[a_col], s=4, color="white", alpha=0.5,
               edgecolors="none", label=f"coil operating points at I={label_I}")
    ax.set_xlabel("|B| (T)"); ax.set_ylabel("angle to out-of-plane vector (deg)")
    ax.set_title("Where the coil sits on the Ic(B, theta) landscape")
    ax.legend(loc="upper right", fontsize=10)
    fig.savefig(os.path.join(params.VIZ_DIR, "ic_landscape.png"),
                dpi=150, bbox_inches="tight")
    plt.close(fig)






def write_summary(df, I_solved, model):
    lines = []
    lines.append(f"Currents actually solved (sweep/field_sweep/): "
                 f"{list(I_solved)} A")
    lines.append(f"Ic model: method={model.method}, "
                 f"output hard-clamped to [{model.Ic_min:.1f}, {model.Ic_max:.1f}] A")
    lines.append(f"Locations analyzed: {len(df)}")
    for status in ["ok", "never_quenched", "quenched_at_min"]:
        n = int((df["status"] == status).sum())
        lines.append(f"  status={status}: {n} ({100*n/len(df):.1f}%)")

    ok = df[df["status"] == "ok"]
    if not ok.empty:
        worst = ok.loc[ok["quench_current_A"].idxmin()]
        lines.append("")
        lines.append(f"Weakest point: quench current = {worst['quench_current_A']:.2f} A "
                      f"at (x={worst['x']:.4f}, y={worst['y']:.4f}, z={worst['z']:.4f}), "
                      f"s={worst['s']:.4f} m")
        lines.append(f"Quench current distribution: "
                      f"min={ok['quench_current_A'].min():.2f} A, "
                      f"5th pct={ok['quench_current_A'].quantile(0.05):.2f} A, "
                      f"median={ok['quench_current_A'].median():.2f} A, "
                      f"max={ok['quench_current_A'].max():.2f} A")

    if (df["status"] == "never_quenched").any():
        lines.append("")
        lines.append("Some locations never quenched within the solved current "
                      f"range ([{I_solved.min()}, {I_solved.max()}] A) -- add "
                      "higher currents to params.sweep_currents and rerun "
                      "solve_sweep.py to find their quench current.")
    if (df["status"] == "quenched_at_min").any():
        lines.append("Some locations already quenched at the lowest solved "
                      "current -- add lower currents to params.sweep_currents "
                      "to localize them more precisely.")

    text = "\n".join(lines)
    with open(os.path.join(params.SWEEP_DIR, "quench_summary.txt"), "w") as f:
        f.write(text + "\n")
    print(text)


def main():
    model = IcModel()  # linear, hard-clamped -- see physics/ic_model.py
    df, extra, frac_clipped = build_dataframe(model)

    if frac_clipped > 0:
        print(f"\nNOTE: {100*frac_clipped:.1f}% of (current, field) "
              f"evaluations needed field-clipping to this dataset's measured "
              f"range [{model.B_min}, {model.B_max}] T. If this is large, "
              "params.sweep_currents is likely too high for this geometry -- "
              "lower it and rerun solve_sweep.py rather than trusting the "
              "clamped answer.\n")

    df.to_csv(os.path.join(params.SWEEP_DIR, "quench_results.csv"), index=False)
    plot_ic_landscape(df, extra, model)
    write_summary(df, extra["I_solved"], model)

    written = ["sweep/quench_results.csv", "sweep/quench_summary.txt",
               "visualization/ic_landscape.png"]
    print("\nWrote " + ", ".join(written))

    # ════════════════════════════════════════════════════════════════════
    # PERFORMANCE SUMMARY
    # ════════════════════════════════════════════════════════════════════
    ok = df[df["status"] == "ok"]
    nq = df[df["status"] == "never_quenched"]
    print()
    print("=" * 65)
    print(" CONFIGURATION PERFORMANCE SUMMARY")
    print("=" * 65)
    g_mm = getattr(params, "coil_half_gap", 0) * 1e3
    print(f"  n_turns      = {params.n_turns}")
    print(f"  total turns  = {params.n_turns_total}")
    print(f"  Winding pack : {params.pack_x_mm:.0f} mm × "
          f"{params.pack_y_mm:.0f} mm × {params.pack_z_mm:.0f} mm  (x × y × z)")
    print(f"  Bore radius  : {params.bore_inner_r_mm:.1f} mm")
    print(f"  Tape length  : {params.tape_length_m:.0f} m  "
          f"({params.tape_length_m/1000:.2f} km)")
    print(f"  coil_half_gap: {g_mm:.0f} mm  "
          f"(c-to-c {2*g_mm:.0f} mm, face-face {2*g_mm-params.pack_z_mm:.0f} mm)")
    never_pct = 100*len(nq)/max(len(df), 1)
    warn = "  ← raise sweep_I_max" if never_pct > 5 else ""
    print(f"  never-quenched: {len(nq)} cells ({never_pct:.1f}%){warn}")
    if not ok.empty:
        Iq = ok["quench_current_A"].values
        print(f"  Min quench   : {np.min(Iq):.1f} A/turn  (weakest cell)")
        print(f"  5th pct      : {np.percentile(Iq,5):.1f} A/turn")
        print(f"  Median       : {np.median(Iq):.1f} A/turn")
        I_min_q = float(np.min(Iq))
        npz_path = params.fields_npz_filename
        if os.path.exists(npz_path):
            try:
                _npz = np.load(npz_path)
                I_ref = float(_npz["I_solved"])
                # multilayer: resolves each layer's own z/radial position
                # instead of treating the whole winding as one filament at
                # a single nominal radius -- that approximation is only
                # valid when the winding-pack cross-section is small
                # compared to a/coil_half_gap (see coil2_field.py), which
                # doesn't hold for small optimized coils.
                from coil2_field import compute_both_coils_field_multilayer
                bore_pt = np.array([[0.0, 0.0, getattr(params, "coil_half_gap", 0)]])
                B_b = compute_both_coils_field_multilayer(
                    bore_pt, I_per_turn=I_ref)
                B_ref = float(np.linalg.norm(B_b))
                print(f"  Bore field at midplane (Biot-Savart):")
                print(f"    At I_ref = {I_ref:.0f} A/turn    : {B_ref:.4f} T")
                print(f"    At I_design ({params.I_design:.0f} A/turn): "
                      f"{B_ref*params.I_design/I_ref:.3f} T")
                B_at_q = B_ref * I_min_q / I_ref
                print(f"    At I_min_quench ({I_min_q:.0f} A/turn): "
                      f"{B_at_q:.3f} T  ← peak before quench")
                I_10T = 10.0 / B_ref * I_ref if B_ref > 0 else float("inf")
                if I_10T <= I_min_q:
                    print(f"  10 T: need {I_10T:.0f} A/turn → "
                          f"safety factor {I_min_q/I_10T:.2f}×  ✓ ACHIEVABLE")
                else:
                    print(f"  10 T: need {I_10T:.0f} A/turn → "
                          f"quench at {I_min_q:.0f} A/turn  ✗  "
                          f"(max {B_at_q:.2f} T = {100*B_at_q/10:.0f}% of target)")
                print(f"  Safety factor at I_design: "
                      f"{I_min_q:.0f}/{params.I_design:.0f} = "
                      f"{I_min_q/params.I_design:.2f}×")
            except Exception as e:
                print(f"  (bore field estimate unavailable: {e})")
        # Operating-point re-solve
        I_op = max(round(I_min_q - 5.0, 1), 1.0)
        print(f"\n  Re-solving at {I_op:.1f} A/turn (I_min_quench − 5) …")
        import subprocess, sys as _sys
        solve_py = os.path.join(
            os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
            "solve", "solve.py")
        r = subprocess.run([_sys.executable, solve_py, "--current", str(I_op)],
                           env=os.environ.copy())
        if r.returncode == 0:
            print(f"  racetrack_fields.npz updated → {I_op:.1f} A/turn")
            print(f"  Re-run visualization scripts to see near-quench field maps.")
        else:
            print(f"  Solve failed.  Run manually:")
            print(f"    python3 solve/solve.py --current {I_op}")
    print("=" * 65)


if __name__ == "__main__":
    main()
