"""
make_optimal_configuration.py
==============================
Poster figure: the champion design's isometric |B| render, generated by
the existing plot_field_poster.py machinery (wedge-cutaway point cloud,
white background, poster styling) -- just redirected into
visualization/for poster/ under a clearer name.

Input: solve/racetrack_fields.npz (must be at I_solved = params.I_design;
run solve/solve.py first if it was last left at a different current, e.g.
by sweep/quench_sweep.py's near-quench re-solve).

Output: visualization/for poster/optimal_configuration.png
"""
import os, sys
import numpy as np

_HERE = os.path.dirname(os.path.abspath(__file__))
_VIZ  = os.path.dirname(_HERE)
_ROOT = os.path.dirname(_VIZ)
for _p in (_ROOT, _VIZ, os.path.join(_ROOT, "physics")):
    if _p not in sys.path:
        sys.path.insert(0, _p)

import params
from plot_field_poster import plot_field_poster

if __name__ == "__main__":
    npz_path = params.fields_npz_filename
    data = np.load(npz_path)
    I_solved = float(data["I_solved"])
    if abs(I_solved - params.I_design) > 0.5:
        print(f"WARNING: racetrack_fields.npz is at I={I_solved:.1f} A, "
              f"not I_design={params.I_design:.1f} A -- "
              f"re-run solve/solve.py before trusting this figure.")
    plot_field_poster(data, out_name="for poster/optimal_configuration.png")
