"""
make_optimal_configuration.py
==============================
Poster figure: the champion design's isometric hoop-stress render,
generated by the existing plot_field_poster.py machinery (wedge-cutaway
point cloud, white background, poster styling) -- just redirected into
visualization/for poster/ under a clearer name.

2026-09-05: recolored from |B| to hoop stress, per user request ("just
calculate the hoop stress everywhere"). validation/mechanical_stress_
check.py's own hoop formula, sigma_hoop = f_n * r, is only rigorously a
"hoop" stress where r is a genuine radius of curvature -- true in the
curved end-caps (r = distance to that cap's own center (+-L, 0)), but
undefined/divergent in the straight legs, where the racetrack centerline
has zero curvature (r -> infinity). To get a well-defined, non-diverging
number on every single cell (not just the caps) instead, this uses r =
distance to the NEAREST cap center for every cell, straight-leg cells
included -- the same r_c already used for cap cells in
mechanical_stress_check.py, just no longer restricted to |x|>L. This
stays small and well-behaved here specifically because this design's
straight-section half-length L=b-a=5.4mm is tiny next to the winding
pack's outer radius a_out~44mm, so nearest-cap-center distance never
blows up the way true curvature-radius would. It is NOT the same
quantity as the straight-leg "transverse (delamination-direction)
stress" mechanical_stress_check.py reports separately (that one has its
own, different, already-validated physical basis) -- treat this map as
a single extended hoop-stress estimate, not a replacement for that
number. Sign (tension/compression) is discarded; the colorbar shows
|sigma_hoop|, matching how the |B| version showed a magnitude too.

Input: solve/racetrack_fields.npz (must be at I_solved = params.I_design;
run solve/solve.py first if it was last left at a different current, e.g.
by sweep/quench_sweep.py's near-quench re-solve).

Output: visualization/for poster/optimal_configuration.png
"""
import os, sys
import numpy as np

_HERE = os.path.dirname(os.path.abspath(__file__))
_VIZ  = os.path.dirname(_HERE)
_ROOT = os.path.dirname(_VIZ)
for _p in (_ROOT, _VIZ, os.path.join(_ROOT, "physics")):
    if _p not in sys.path:
        sys.path.insert(0, _p)

import params
from current_source import tangent_xy, normal_xy
from plot_field_poster import plot_field_poster


def compute_hoop_stress_everywhere(data):
    """Per-cell |sigma_hoop| [Pa] on the raw (1/8-domain) coil cells stored
    in racetrack_fields.npz, extending mechanical_stress_check.py's cap-only
    formula (sigma_hoop = f_n * r_c) to every cell via nearest-cap-center
    distance -- see this file's module docstring for the caveat."""
    I_op = float(data["I_solved"])
    L = params.b - params.a
    cents = data["coil_centroids"]
    B = data["coil_B"]

    Je = I_op / (params.t * params.w)
    tx, ty = tangent_xy(cents[:, 0], cents[:, 1], L)
    nx, ny = normal_xy(cents[:, 0], cents[:, 1], L)
    t_hat = np.column_stack([tx, ty, np.zeros(len(cents))])
    n_hat = np.column_stack([nx, ny, np.zeros(len(cents))])

    f = np.cross(Je * t_hat, B)                      # [N/m^3]
    f_n = np.einsum("ij,ij->i", f, n_hat)

    cx = np.where(cents[:, 0] > 0, L, -L)             # nearest cap center
    r_c = np.hypot(cents[:, 0] - cx, cents[:, 1])
    return np.abs(f_n * r_c)                          # [Pa]


if __name__ == "__main__":
    npz_path = params.fields_npz_filename
    data = np.load(npz_path)
    I_solved = float(data["I_solved"])
    if abs(I_solved - params.I_design) > 0.5:
        print(f"WARNING: racetrack_fields.npz is at I={I_solved:.1f} A, "
              f"not I_design={params.I_design:.1f} A -- "
              f"re-run solve/solve.py before trusting this figure.")
    sigma_hoop = compute_hoop_stress_everywhere(data)
    print(f"  hoop stress (extended): max {sigma_hoop.max()/1e6:.1f} MPa, "
          f"mean {sigma_hoop.mean()/1e6:.1f} MPa")
    plot_field_poster(data, out_name="for poster/optimal_configuration.png",
                      value_raw=sigma_hoop/1e6, cbar_label="|σ_hoop|  (MPa)")
