#define _CFFI_

/* We try to define Py_LIMITED_API before including Python.h.

   Mess: we can only define it if Py_DEBUG, Py_TRACE_REFS and
   Py_REF_DEBUG are not defined.  This is a best-effort approximation:
   we can learn about Py_DEBUG from pyconfig.h, but it is unclear if
   the same works for the other two macros.  Py_DEBUG implies them,
   but not the other way around.

   The implementation is messy (issue #350): on Windows, with _MSC_VER,
   we have to define Py_LIMITED_API even before including pyconfig.h.
   In that case, we guess what pyconfig.h will do to the macros above,
   and check our guess after the #include.

   Note that on Windows, with CPython 3.x, you need >= 3.5 and virtualenv
   version >= 16.0.0.  With older versions of either, you don't get a
   copy of PYTHON3.DLL in the virtualenv.  We can't check the version of
   CPython *before* we even include pyconfig.h.  ffi.set_source() puts
   a ``#define _CFFI_NO_LIMITED_API'' at the start of this file if it is
   running on Windows < 3.5, as an attempt at fixing it, but that's
   arguably wrong because it may not be the target version of Python.
   Still better than nothing I guess.  As another workaround, you can
   remove the definition of Py_LIMITED_API here.

   See also 'py_limited_api' in cffi/setuptools_ext.py.
*/
#if !defined(_CFFI_USE_EMBEDDING) && !defined(Py_LIMITED_API)
#  ifdef _MSC_VER
#    if !defined(_DEBUG) && !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#    include <pyconfig.h>
     /* sanity-check: Py_LIMITED_API will cause crashes if any of these
        are also defined.  Normally, the Python file PC/pyconfig.h does not
        cause any of these to be defined, with the exception that _DEBUG
        causes Py_DEBUG.  Double-check that. */
#    ifdef Py_LIMITED_API
#      if defined(Py_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_DEBUG, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_TRACE_REFS)
#        error "pyconfig.h unexpectedly defines Py_TRACE_REFS, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_REF_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_REF_DEBUG, but Py_LIMITED_API is set"
#      endif
#    endif
#  else
#    include <pyconfig.h>
#    if !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#  endif
#endif

#include <Python.h>
#ifdef __cplusplus
extern "C" {
#endif
#include <stddef.h>

/* This part is from file 'cffi/parse_c_type.h'.  It is copied at the
   beginning of C sources generated by CFFI's ffi.set_source(). */

typedef void *_cffi_opcode_t;

#define _CFFI_OP(opcode, arg)   (_cffi_opcode_t)(opcode | (((uintptr_t)(arg)) << 8))
#define _CFFI_GETOP(cffi_opcode)    ((unsigned char)(uintptr_t)cffi_opcode)
#define _CFFI_GETARG(cffi_opcode)   (((intptr_t)cffi_opcode) >> 8)

#define _CFFI_OP_PRIMITIVE       1
#define _CFFI_OP_POINTER         3
#define _CFFI_OP_ARRAY           5
#define _CFFI_OP_OPEN_ARRAY      7
#define _CFFI_OP_STRUCT_UNION    9
#define _CFFI_OP_ENUM           11
#define _CFFI_OP_FUNCTION       13
#define _CFFI_OP_FUNCTION_END   15
#define _CFFI_OP_NOOP           17
#define _CFFI_OP_BITFIELD       19
#define _CFFI_OP_TYPENAME       21
#define _CFFI_OP_CPYTHON_BLTN_V 23   // varargs
#define _CFFI_OP_CPYTHON_BLTN_N 25   // noargs
#define _CFFI_OP_CPYTHON_BLTN_O 27   // O  (i.e. a single arg)
#define _CFFI_OP_CONSTANT       29
#define _CFFI_OP_CONSTANT_INT   31
#define _CFFI_OP_GLOBAL_VAR     33
#define _CFFI_OP_DLOPEN_FUNC    35
#define _CFFI_OP_DLOPEN_CONST   37
#define _CFFI_OP_GLOBAL_VAR_F   39
#define _CFFI_OP_EXTERN_PYTHON  41

#define _CFFI_PRIM_VOID          0
#define _CFFI_PRIM_BOOL          1
#define _CFFI_PRIM_CHAR          2
#define _CFFI_PRIM_SCHAR         3
#define _CFFI_PRIM_UCHAR         4
#define _CFFI_PRIM_SHORT         5
#define _CFFI_PRIM_USHORT        6
#define _CFFI_PRIM_INT           7
#define _CFFI_PRIM_UINT          8
#define _CFFI_PRIM_LONG          9
#define _CFFI_PRIM_ULONG        10
#define _CFFI_PRIM_LONGLONG     11
#define _CFFI_PRIM_ULONGLONG    12
#define _CFFI_PRIM_FLOAT        13
#define _CFFI_PRIM_DOUBLE       14
#define _CFFI_PRIM_LONGDOUBLE   15

#define _CFFI_PRIM_WCHAR        16
#define _CFFI_PRIM_INT8         17
#define _CFFI_PRIM_UINT8        18
#define _CFFI_PRIM_INT16        19
#define _CFFI_PRIM_UINT16       20
#define _CFFI_PRIM_INT32        21
#define _CFFI_PRIM_UINT32       22
#define _CFFI_PRIM_INT64        23
#define _CFFI_PRIM_UINT64       24
#define _CFFI_PRIM_INTPTR       25
#define _CFFI_PRIM_UINTPTR      26
#define _CFFI_PRIM_PTRDIFF      27
#define _CFFI_PRIM_SIZE         28
#define _CFFI_PRIM_SSIZE        29
#define _CFFI_PRIM_INT_LEAST8   30
#define _CFFI_PRIM_UINT_LEAST8  31
#define _CFFI_PRIM_INT_LEAST16  32
#define _CFFI_PRIM_UINT_LEAST16 33
#define _CFFI_PRIM_INT_LEAST32  34
#define _CFFI_PRIM_UINT_LEAST32 35
#define _CFFI_PRIM_INT_LEAST64  36
#define _CFFI_PRIM_UINT_LEAST64 37
#define _CFFI_PRIM_INT_FAST8    38
#define _CFFI_PRIM_UINT_FAST8   39
#define _CFFI_PRIM_INT_FAST16   40
#define _CFFI_PRIM_UINT_FAST16  41
#define _CFFI_PRIM_INT_FAST32   42
#define _CFFI_PRIM_UINT_FAST32  43
#define _CFFI_PRIM_INT_FAST64   44
#define _CFFI_PRIM_UINT_FAST64  45
#define _CFFI_PRIM_INTMAX       46
#define _CFFI_PRIM_UINTMAX      47
#define _CFFI_PRIM_FLOATCOMPLEX 48
#define _CFFI_PRIM_DOUBLECOMPLEX 49
#define _CFFI_PRIM_CHAR16       50
#define _CFFI_PRIM_CHAR32       51

#define _CFFI__NUM_PRIM         52
#define _CFFI__UNKNOWN_PRIM           (-1)
#define _CFFI__UNKNOWN_FLOAT_PRIM     (-2)
#define _CFFI__UNKNOWN_LONG_DOUBLE    (-3)

#define _CFFI__IO_FILE_STRUCT         (-1)


struct _cffi_global_s {
    const char *name;
    void *address;
    _cffi_opcode_t type_op;
    void *size_or_direct_fn;  // OP_GLOBAL_VAR: size, or 0 if unknown
                              // OP_CPYTHON_BLTN_*: addr of direct function
};

struct _cffi_getconst_s {
    unsigned long long value;
    const struct _cffi_type_context_s *ctx;
    int gindex;
};

struct _cffi_struct_union_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_STRUCT_UNION
    int flags;               // _CFFI_F_* flags below
    size_t size;
    int alignment;
    int first_field_index;   // -> _cffi_fields array
    int num_fields;
};
#define _CFFI_F_UNION         0x01   // is a union, not a struct
#define _CFFI_F_CHECK_FIELDS  0x02   // complain if fields are not in the
                                     // "standard layout" or if some are missing
#define _CFFI_F_PACKED        0x04   // for CHECK_FIELDS, assume a packed struct
#define _CFFI_F_EXTERNAL      0x08   // in some other ffi.include()
#define _CFFI_F_OPAQUE        0x10   // opaque

struct _cffi_field_s {
    const char *name;
    size_t field_offset;
    size_t field_size;
    _cffi_opcode_t field_type_op;
};

struct _cffi_enum_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_ENUM
    int type_prim;           // _CFFI_PRIM_xxx
    const char *enumerators; // comma-delimited string
};

struct _cffi_typename_s {
    const char *name;
    int type_index;   /* if opaque, points to a possibly artificial
                         OP_STRUCT which is itself opaque */
};

struct _cffi_type_context_s {
    _cffi_opcode_t *types;
    const struct _cffi_global_s *globals;
    const struct _cffi_field_s *fields;
    const struct _cffi_struct_union_s *struct_unions;
    const struct _cffi_enum_s *enums;
    const struct _cffi_typename_s *typenames;
    int num_globals;
    int num_struct_unions;
    int num_enums;
    int num_typenames;
    const char *const *includes;
    int num_types;
    int flags;      /* future extension */
};

struct _cffi_parse_info_s {
    const struct _cffi_type_context_s *ctx;
    _cffi_opcode_t *output;
    unsigned int output_size;
    size_t error_location;
    const char *error_message;
};

struct _cffi_externpy_s {
    const char *name;
    size_t size_of_result;
    void *reserved1, *reserved2;
};

#ifdef _CFFI_INTERNAL
static int parse_c_type(struct _cffi_parse_info_s *info, const char *input);
static int search_in_globals(const struct _cffi_type_context_s *ctx,
                             const char *search, size_t search_len);
static int search_in_struct_unions(const struct _cffi_type_context_s *ctx,
                                   const char *search, size_t search_len);
#endif

/* this block of #ifs should be kept exactly identical between
   c/_cffi_backend.c, cffi/vengine_cpy.py, cffi/vengine_gen.py
   and cffi/_cffi_include.h */
#if defined(_MSC_VER)
# include <malloc.h>   /* for alloca() */
# if _MSC_VER < 1600   /* MSVC < 2010 */
   typedef __int8 int8_t;
   typedef __int16 int16_t;
   typedef __int32 int32_t;
   typedef __int64 int64_t;
   typedef unsigned __int8 uint8_t;
   typedef unsigned __int16 uint16_t;
   typedef unsigned __int32 uint32_t;
   typedef unsigned __int64 uint64_t;
   typedef __int8 int_least8_t;
   typedef __int16 int_least16_t;
   typedef __int32 int_least32_t;
   typedef __int64 int_least64_t;
   typedef unsigned __int8 uint_least8_t;
   typedef unsigned __int16 uint_least16_t;
   typedef unsigned __int32 uint_least32_t;
   typedef unsigned __int64 uint_least64_t;
   typedef __int8 int_fast8_t;
   typedef __int16 int_fast16_t;
   typedef __int32 int_fast32_t;
   typedef __int64 int_fast64_t;
   typedef unsigned __int8 uint_fast8_t;
   typedef unsigned __int16 uint_fast16_t;
   typedef unsigned __int32 uint_fast32_t;
   typedef unsigned __int64 uint_fast64_t;
   typedef __int64 intmax_t;
   typedef unsigned __int64 uintmax_t;
# else
#  include <stdint.h>
# endif
# if _MSC_VER < 1800   /* MSVC < 2013 */
#  ifndef __cplusplus
    typedef unsigned char _Bool;
#  endif
# endif
# define _cffi_float_complex_t   _Fcomplex    /* include <complex.h> for it */
# define _cffi_double_complex_t  _Dcomplex    /* include <complex.h> for it */
#else
# include <stdint.h>
# if (defined (__SVR4) && defined (__sun)) || defined(_AIX) || defined(__hpux)
#  include <alloca.h>
# endif
# define _cffi_float_complex_t   float _Complex
# define _cffi_double_complex_t  double _Complex
#endif

#ifdef __GNUC__
# define _CFFI_UNUSED_FN  __attribute__((unused))
#else
# define _CFFI_UNUSED_FN  /* nothing */
#endif

#ifdef __cplusplus
# ifndef _Bool
   typedef bool _Bool;   /* semi-hackish: C++ has no _Bool; bool is builtin */
# endif
#endif

/**********  CPython-specific section  **********/
#ifndef PYPY_VERSION


#if PY_MAJOR_VERSION >= 3
# define PyInt_FromLong PyLong_FromLong
#endif

#define _cffi_from_c_double PyFloat_FromDouble
#define _cffi_from_c_float PyFloat_FromDouble
#define _cffi_from_c_long PyInt_FromLong
#define _cffi_from_c_ulong PyLong_FromUnsignedLong
#define _cffi_from_c_longlong PyLong_FromLongLong
#define _cffi_from_c_ulonglong PyLong_FromUnsignedLongLong
#define _cffi_from_c__Bool PyBool_FromLong

#define _cffi_to_c_double PyFloat_AsDouble
#define _cffi_to_c_float PyFloat_AsDouble

#define _cffi_from_c_int(x, type)                                        \
    (((type)-1) > 0 ? /* unsigned */                                     \
        (sizeof(type) < sizeof(long) ?                                   \
            PyInt_FromLong((long)x) :                                    \
         sizeof(type) == sizeof(long) ?                                  \
            PyLong_FromUnsignedLong((unsigned long)x) :                  \
            PyLong_FromUnsignedLongLong((unsigned long long)x)) :        \
        (sizeof(type) <= sizeof(long) ?                                  \
            PyInt_FromLong((long)x) :                                    \
            PyLong_FromLongLong((long long)x)))

#define _cffi_to_c_int(o, type)                                          \
    ((type)(                                                             \
     sizeof(type) == 1 ? (((type)-1) > 0 ? (type)_cffi_to_c_u8(o)        \
                                         : (type)_cffi_to_c_i8(o)) :     \
     sizeof(type) == 2 ? (((type)-1) > 0 ? (type)_cffi_to_c_u16(o)       \
                                         : (type)_cffi_to_c_i16(o)) :    \
     sizeof(type) == 4 ? (((type)-1) > 0 ? (type)_cffi_to_c_u32(o)       \
                                         : (type)_cffi_to_c_i32(o)) :    \
     sizeof(type) == 8 ? (((type)-1) > 0 ? (type)_cffi_to_c_u64(o)       \
                                         : (type)_cffi_to_c_i64(o)) :    \
     (Py_FatalError("unsupported size for type " #type), (type)0)))

#define _cffi_to_c_i8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[1])
#define _cffi_to_c_u8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[2])
#define _cffi_to_c_i16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[3])
#define _cffi_to_c_u16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[4])
#define _cffi_to_c_i32                                                   \
                 ((int(*)(PyObject *))_cffi_exports[5])
#define _cffi_to_c_u32                                                   \
                 ((unsigned int(*)(PyObject *))_cffi_exports[6])
#define _cffi_to_c_i64                                                   \
                 ((long long(*)(PyObject *))_cffi_exports[7])
#define _cffi_to_c_u64                                                   \
                 ((unsigned long long(*)(PyObject *))_cffi_exports[8])
#define _cffi_to_c_char                                                  \
                 ((int(*)(PyObject *))_cffi_exports[9])
#define _cffi_from_c_pointer                                             \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[10])
#define _cffi_to_c_pointer                                               \
    ((char *(*)(PyObject *, struct _cffi_ctypedescr *))_cffi_exports[11])
#define _cffi_get_struct_layout                                          \
    not used any more
#define _cffi_restore_errno                                              \
    ((void(*)(void))_cffi_exports[13])
#define _cffi_save_errno                                                 \
    ((void(*)(void))_cffi_exports[14])
#define _cffi_from_c_char                                                \
    ((PyObject *(*)(char))_cffi_exports[15])
#define _cffi_from_c_deref                                               \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[16])
#define _cffi_to_c                                                       \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[17])
#define _cffi_from_c_struct                                              \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[18])
#define _cffi_to_c_wchar_t                                               \
    ((_cffi_wchar_t(*)(PyObject *))_cffi_exports[19])
#define _cffi_from_c_wchar_t                                             \
    ((PyObject *(*)(_cffi_wchar_t))_cffi_exports[20])
#define _cffi_to_c_long_double                                           \
    ((long double(*)(PyObject *))_cffi_exports[21])
#define _cffi_to_c__Bool                                                 \
    ((_Bool(*)(PyObject *))_cffi_exports[22])
#define _cffi_prepare_pointer_call_argument                              \
    ((Py_ssize_t(*)(struct _cffi_ctypedescr *,                           \
                    PyObject *, char **))_cffi_exports[23])
#define _cffi_convert_array_from_object                                  \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[24])
#define _CFFI_CPIDX  25
#define _cffi_call_python                                                \
    ((void(*)(struct _cffi_externpy_s *, char *))_cffi_exports[_CFFI_CPIDX])
#define _cffi_to_c_wchar3216_t                                           \
    ((int(*)(PyObject *))_cffi_exports[26])
#define _cffi_from_c_wchar3216_t                                         \
    ((PyObject *(*)(int))_cffi_exports[27])
#define _CFFI_NUM_EXPORTS 28

struct _cffi_ctypedescr;

static void *_cffi_exports[_CFFI_NUM_EXPORTS];

#define _cffi_type(index)   (                           \
    assert((((uintptr_t)_cffi_types[index]) & 1) == 0), \
    (struct _cffi_ctypedescr *)_cffi_types[index])

static PyObject *_cffi_init(const char *module_name, Py_ssize_t version,
                            const struct _cffi_type_context_s *ctx)
{
    PyObject *module, *o_arg, *new_module;
    void *raw[] = {
        (void *)module_name,
        (void *)version,
        (void *)_cffi_exports,
        (void *)ctx,
    };

    module = PyImport_ImportModule("_cffi_backend");
    if (module == NULL)
        goto failure;

    o_arg = PyLong_FromVoidPtr((void *)raw);
    if (o_arg == NULL)
        goto failure;

    new_module = PyObject_CallMethod(
        module, (char *)"_init_cffi_1_0_external_module", (char *)"O", o_arg);

    Py_DECREF(o_arg);
    Py_DECREF(module);
    return new_module;

  failure:
    Py_XDECREF(module);
    return NULL;
}


#ifdef HAVE_WCHAR_H
typedef wchar_t _cffi_wchar_t;
#else
typedef uint16_t _cffi_wchar_t;   /* same random pick as _cffi_backend.c */
#endif

_CFFI_UNUSED_FN static uint16_t _cffi_to_c_char16_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return (uint16_t)_cffi_to_c_wchar_t(o);
    else
        return (uint16_t)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char16_t(uint16_t x)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

_CFFI_UNUSED_FN static int _cffi_to_c_char32_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return (int)_cffi_to_c_wchar_t(o);
    else
        return (int)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char32_t(unsigned int x)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

union _cffi_union_alignment_u {
    unsigned char m_char;
    unsigned short m_short;
    unsigned int m_int;
    unsigned long m_long;
    unsigned long long m_longlong;
    float m_float;
    double m_double;
    long double m_longdouble;
};

struct _cffi_freeme_s {
    struct _cffi_freeme_s *next;
    union _cffi_union_alignment_u alignment;
};

_CFFI_UNUSED_FN static int
_cffi_convert_array_argument(struct _cffi_ctypedescr *ctptr, PyObject *arg,
                             char **output_data, Py_ssize_t datasize,
                             struct _cffi_freeme_s **freeme)
{
    char *p;
    if (datasize < 0)
        return -1;

    p = *output_data;
    if (p == NULL) {
        struct _cffi_freeme_s *fp = (struct _cffi_freeme_s *)PyObject_Malloc(
            offsetof(struct _cffi_freeme_s, alignment) + (size_t)datasize);
        if (fp == NULL)
            return -1;
        fp->next = *freeme;
        *freeme = fp;
        p = *output_data = (char *)&fp->alignment;
    }
    memset((void *)p, 0, (size_t)datasize);
    return _cffi_convert_array_from_object(p, ctptr, arg);
}

_CFFI_UNUSED_FN static void
_cffi_free_array_arguments(struct _cffi_freeme_s *freeme)
{
    do {
        void *p = (void *)freeme;
        freeme = freeme->next;
        PyObject_Free(p);
    } while (freeme != NULL);
}

/**********  end CPython-specific section  **********/
#else
_CFFI_UNUSED_FN
static void (*_cffi_call_python_org)(struct _cffi_externpy_s *, char *);
# define _cffi_call_python  _cffi_call_python_org
#endif


#define _cffi_array_len(array)   (sizeof(array) / sizeof((array)[0]))

#define _cffi_prim_int(size, sign)                                      \
    ((size) == 1 ? ((sign) ? _CFFI_PRIM_INT8  : _CFFI_PRIM_UINT8)  :    \
     (size) == 2 ? ((sign) ? _CFFI_PRIM_INT16 : _CFFI_PRIM_UINT16) :    \
     (size) == 4 ? ((sign) ? _CFFI_PRIM_INT32 : _CFFI_PRIM_UINT32) :    \
     (size) == 8 ? ((sign) ? _CFFI_PRIM_INT64 : _CFFI_PRIM_UINT64) :    \
     _CFFI__UNKNOWN_PRIM)

#define _cffi_prim_float(size)                                          \
    ((size) == sizeof(float) ? _CFFI_PRIM_FLOAT :                       \
     (size) == sizeof(double) ? _CFFI_PRIM_DOUBLE :                     \
     (size) == sizeof(long double) ? _CFFI__UNKNOWN_LONG_DOUBLE :       \
     _CFFI__UNKNOWN_FLOAT_PRIM)

#define _cffi_check_int(got, got_nonpos, expected)      \
    ((got_nonpos) == (expected <= 0) &&                 \
     (got) == (unsigned long long)expected)

#ifdef MS_WIN32
# define _cffi_stdcall  __stdcall
#else
# define _cffi_stdcall  /* nothing */
#endif

#ifdef __cplusplus
}
#endif

/************************************************************/


// This code conforms with the UFCx specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.11.0.
//
// This code was generated with the following options:
//
//  {'epsilon': 1e-14,
//   'language': 'C',
//   'part': 'full',
//   'scalar_type': <class 'numpy.float64'>,
//   'sum_factorization': False,
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'verbosity': 30}

#include <math.h>
#include <stdalign.h>
#include <stdlib.h>
#include <string.h>
#include <ufcx.h>



// Code for integral integral_b9d745df7c51ad241ad2646bcd287b24a7aa65fe_tetrahedron

void tabulate_tensor_integral_b9d745df7c51ad241ad2646bcd287b24a7aa65fe_tetrahedron(double* restrict A,
                                    const double* restrict w,
                                    const double* restrict c,
                                    const double* restrict coordinate_dofs,
                                    const int* restrict entity_local_index,
                                    const uint8_t* restrict quadrature_permutation,
                                    void* custom_data)
{
// Quadrature rules
static const double weights_fad[4] = {0.04166666666666666, 0.04166666666666666, 0.04166666666666666, 0.04166666666666666};
// Precomputed values of basis functions and precomputations
// FE* dimensions: [permutation][entities][points][dofs]
static const double FE1_C0_D010_Qfad[1][1][1][4] = {{{{-1.0, 0.0, 1.0, 0.0}}}};
static const double FE1_C0_D100_Qfad[1][1][1][4] = {{{{-1.0, 1.0, 0.0, 0.0}}}};
static const double FE1_C1_D001_Qfad[1][1][1][4] = {{{{-1.0, 0.0, 0.0, 1.0}}}};
static const double FE2_C0_D001_Qfad[1][1][1][6] = {{{{0.0, -1.0, 0.0, 1.0, 0.0, -1.0}}}};
static const double FE2_C0_D010_Qfad[1][1][1][6] = {{{{0.0, 0.0, -1.0, 0.0, 1.0, -1.0}}}};
static const double FE2_C0_Qfad[1][1][4][6] = {{{{0.0, -0.1381966011250125, -0.1381966011250125, 0.1381966011250125, 0.1381966011250125, 0.7236067977499752},
  {0.0, -0.1381966011250104, -0.5854101966249663, 0.1381966011250125, 0.5854101966249643, 0.2763932022500233},
  {0.0, -0.5854101966249664, -0.1381966011250104, 0.5854101966249643, 0.1381966011250125, 0.2763932022500232},
  {0.0, -0.1381966011250083, -0.1381966011250083, 0.1381966011250083, 0.1381966011250083, 0.7236067977499836}}}};
static const double FE2_C1_D001_Qfad[1][1][1][6] = {{{{-1.0, 0.0, 0.0, 1.0, -1.0, 0.0}}}};
static const double FE2_C1_D100_Qfad[1][1][1][6] = {{{{0.0, 0.0, 1.0, 0.0, -1.0, 1.0}}}};
static const double FE2_C1_Qfad[1][1][4][6] = {{{{-0.1381966011250102, 0.0, 0.585410196624966, 0.1381966011250124, 0.2763932022500237, 0.5854101966249639},
  {-0.1381966011250124, 0.0, 0.1381966011250124, 0.1381966011250124, 0.7236067977499751, 0.1381966011250124},
  {-0.5854101966249661, 0.0, 0.1381966011250103, 0.5854101966249639, 0.2763932022500236, 0.1381966011250124},
  {-0.1381966011250081, 0.0, 0.1381966011250081, 0.1381966011250081, 0.7236067977499837, 0.1381966011250081}}}};
static const double FE2_C2_D010_Qfad[1][1][1][6] = {{{{1.0, 0.0, 0.0, -1.0, 1.0, 0.0}}}};
static const double FE2_C2_D100_Qfad[1][1][1][6] = {{{{0.0, 1.0, 0.0, -1.0, 0.0, 1.0}}}};
static const double FE2_C2_Qfad[1][1][4][6] = {{{{0.1381966011250103, 0.585410196624966, 0.0, 0.2763932022500236, 0.1381966011250126, 0.585410196624964},
  {0.5854101966249662, 0.1381966011250103, 0.0, 0.2763932022500235, 0.5854101966249641, 0.1381966011250124},
  {0.1381966011250125, 0.1381966011250123, 0.0, 0.7236067977499752, 0.1381966011250125, 0.1381966011250123},
  {0.1381966011250081, 0.1381966011250081, 0.0, 0.7236067977499836, 0.1381966011250082, 0.1381966011250081}}}};
// ------------------------ 
// Section: Jacobian
// Inputs: FE1_C1_D001_Qfad, FE1_C0_D100_Qfad, FE1_C0_D010_Qfad, coordinate_dofs
// Outputs: J0_c0, J0_c5, J0_c7, J0_c8, J0_c6, J0_c2, J0_c3, J0_c1, J0_c4
double J0_c0 = 0.0;
double J0_c4 = 0.0;
double J0_c1 = 0.0;
double J0_c3 = 0.0;
double J0_c8 = 0.0;
double J0_c5 = 0.0;
double J0_c7 = 0.0;
double J0_c6 = 0.0;
double J0_c2 = 0.0;
{
  for (int ic = 0; ic < 4; ++ic)
  {
    J0_c0 += coordinate_dofs[(ic) * 3] * FE1_C0_D100_Qfad[0][0][0][ic];
    J0_c4 += coordinate_dofs[(ic) * 3 + 1] * FE1_C0_D010_Qfad[0][0][0][ic];
    J0_c1 += coordinate_dofs[(ic) * 3] * FE1_C0_D010_Qfad[0][0][0][ic];
    J0_c3 += coordinate_dofs[(ic) * 3 + 1] * FE1_C0_D100_Qfad[0][0][0][ic];
    J0_c8 += coordinate_dofs[(ic) * 3 + 2] * FE1_C1_D001_Qfad[0][0][0][ic];
    J0_c5 += coordinate_dofs[(ic) * 3 + 1] * FE1_C1_D001_Qfad[0][0][0][ic];
    J0_c7 += coordinate_dofs[(ic) * 3 + 2] * FE1_C0_D010_Qfad[0][0][0][ic];
    J0_c6 += coordinate_dofs[(ic) * 3 + 2] * FE1_C0_D100_Qfad[0][0][0][ic];
    J0_c2 += coordinate_dofs[(ic) * 3] * FE1_C1_D001_Qfad[0][0][0][ic];
  }
}
// ------------------------ 
double sp_fad_0 = J0_c0 * J0_c4;
double sp_fad_1 = J0_c1 * J0_c3;
double sp_fad_2 = -sp_fad_1;
double sp_fad_3 = sp_fad_0 + sp_fad_2;
double sp_fad_4 = J0_c4 * J0_c8;
double sp_fad_5 = J0_c5 * J0_c7;
double sp_fad_6 = -sp_fad_5;
double sp_fad_7 = sp_fad_4 + sp_fad_6;
double sp_fad_8 = J0_c0 * sp_fad_7;
double sp_fad_9 = J0_c3 * J0_c8;
double sp_fad_10 = J0_c5 * J0_c6;
double sp_fad_11 = -sp_fad_10;
double sp_fad_12 = sp_fad_9 + sp_fad_11;
double sp_fad_13 = -J0_c1;
double sp_fad_14 = sp_fad_12 * sp_fad_13;
double sp_fad_15 = sp_fad_8 + sp_fad_14;
double sp_fad_16 = J0_c3 * J0_c7;
double sp_fad_17 = J0_c4 * J0_c6;
double sp_fad_18 = -sp_fad_17;
double sp_fad_19 = sp_fad_16 + sp_fad_18;
double sp_fad_20 = J0_c2 * sp_fad_19;
double sp_fad_21 = sp_fad_15 + sp_fad_20;
double sp_fad_22 = sp_fad_3 / sp_fad_21;
double sp_fad_23 = J0_c2 * J0_c3;
double sp_fad_24 = J0_c0 * J0_c5;
double sp_fad_25 = -sp_fad_24;
double sp_fad_26 = sp_fad_23 + sp_fad_25;
double sp_fad_27 = sp_fad_26 / sp_fad_21;
double sp_fad_28 = sp_fad_7 / sp_fad_21;
double sp_fad_29 = sp_fad_22 * sp_fad_28;
double sp_fad_30 = sp_fad_27 * sp_fad_28;
double sp_fad_31 = J0_c1 * J0_c5;
double sp_fad_32 = J0_c2 * J0_c4;
double sp_fad_33 = -sp_fad_32;
double sp_fad_34 = sp_fad_31 + sp_fad_33;
double sp_fad_35 = sp_fad_34 / sp_fad_21;
double sp_fad_36 = -J0_c8;
double sp_fad_37 = J0_c3 * sp_fad_36;
double sp_fad_38 = sp_fad_10 + sp_fad_37;
double sp_fad_39 = sp_fad_38 / sp_fad_21;
double sp_fad_40 = sp_fad_22 * sp_fad_39;
double sp_fad_41 = sp_fad_35 * sp_fad_39;
double sp_fad_42 = sp_fad_19 / sp_fad_21;
double sp_fad_43 = sp_fad_35 * sp_fad_42;
double sp_fad_44 = sp_fad_27 * sp_fad_42;
double sp_fad_45 = -sp_fad_43;
double sp_fad_46 = -sp_fad_41;
double sp_fad_47 = -sp_fad_44;
double sp_fad_48 = -sp_fad_30;
double sp_fad_49 = -sp_fad_29;
double sp_fad_50 = -sp_fad_40;
double sp_fad_51 = sp_fad_45 + sp_fad_29;
double sp_fad_52 = sp_fad_46 + sp_fad_30;
double sp_fad_53 = sp_fad_47 + sp_fad_40;
double sp_fad_54 = sp_fad_48 + sp_fad_41;
double sp_fad_55 = sp_fad_49 + sp_fad_43;
double sp_fad_56 = sp_fad_50 + sp_fad_44;
double sp_fad_57 = sp_fad_51 * sp_fad_51;
double sp_fad_58 = sp_fad_51 * sp_fad_52;
double sp_fad_59 = sp_fad_51 * sp_fad_53;
double sp_fad_60 = sp_fad_51 * sp_fad_54;
double sp_fad_61 = sp_fad_55 * sp_fad_51;
double sp_fad_62 = sp_fad_56 * sp_fad_51;
double sp_fad_63 = sp_fad_52 * sp_fad_52;
double sp_fad_64 = sp_fad_52 * sp_fad_53;
double sp_fad_65 = sp_fad_52 * sp_fad_54;
double sp_fad_66 = sp_fad_55 * sp_fad_52;
double sp_fad_67 = sp_fad_56 * sp_fad_52;
double sp_fad_68 = sp_fad_53 * sp_fad_53;
double sp_fad_69 = sp_fad_53 * sp_fad_54;
double sp_fad_70 = sp_fad_55 * sp_fad_53;
double sp_fad_71 = sp_fad_56 * sp_fad_53;
double sp_fad_72 = sp_fad_54 * sp_fad_54;
double sp_fad_73 = sp_fad_55 * sp_fad_54;
double sp_fad_74 = sp_fad_56 * sp_fad_54;
double sp_fad_75 = sp_fad_55 * sp_fad_55;
double sp_fad_76 = sp_fad_55 * sp_fad_56;
double sp_fad_77 = sp_fad_56 * sp_fad_56;
double sp_fad_78 = J0_c0 * J0_c8;
double sp_fad_79 = -J0_c2;
double sp_fad_80 = J0_c6 * sp_fad_79;
double sp_fad_81 = sp_fad_78 + sp_fad_80;
double sp_fad_82 = sp_fad_81 / sp_fad_21;
double sp_fad_83 = J0_c1 * J0_c6;
double sp_fad_84 = J0_c0 * J0_c7;
double sp_fad_85 = -sp_fad_84;
double sp_fad_86 = sp_fad_83 + sp_fad_85;
double sp_fad_87 = sp_fad_86 / sp_fad_21;
double sp_fad_88 = sp_fad_35 * sp_fad_87;
double sp_fad_89 = sp_fad_82 * sp_fad_35;
double sp_fad_90 = J0_c2 * J0_c7;
double sp_fad_91 = J0_c8 * sp_fad_13;
double sp_fad_92 = sp_fad_90 + sp_fad_91;
double sp_fad_93 = sp_fad_92 / sp_fad_21;
double sp_fad_94 = sp_fad_27 * sp_fad_87;
double sp_fad_95 = sp_fad_93 * sp_fad_27;
double sp_fad_96 = sp_fad_93 * sp_fad_22;
double sp_fad_97 = sp_fad_82 * sp_fad_22;
double sp_fad_98 = -sp_fad_96;
double sp_fad_99 = -sp_fad_95;
double sp_fad_100 = -sp_fad_97;
double sp_fad_101 = -sp_fad_89;
double sp_fad_102 = -sp_fad_88;
double sp_fad_103 = -sp_fad_94;
double sp_fad_104 = sp_fad_98 + sp_fad_88;
double sp_fad_105 = sp_fad_99 + sp_fad_89;
double sp_fad_106 = sp_fad_100 + sp_fad_94;
double sp_fad_107 = sp_fad_101 + sp_fad_95;
double sp_fad_108 = sp_fad_102 + sp_fad_96;
double sp_fad_109 = sp_fad_103 + sp_fad_97;
double sp_fad_110 = sp_fad_104 * sp_fad_104;
double sp_fad_111 = sp_fad_105 * sp_fad_104;
double sp_fad_112 = sp_fad_104 * sp_fad_106;
double sp_fad_113 = sp_fad_107 * sp_fad_104;
double sp_fad_114 = sp_fad_108 * sp_fad_104;
double sp_fad_115 = sp_fad_109 * sp_fad_104;
double sp_fad_116 = sp_fad_105 * sp_fad_105;
double sp_fad_117 = sp_fad_105 * sp_fad_106;
double sp_fad_118 = sp_fad_105 * sp_fad_107;
double sp_fad_119 = sp_fad_108 * sp_fad_105;
double sp_fad_120 = sp_fad_109 * sp_fad_105;
double sp_fad_121 = sp_fad_106 * sp_fad_106;
double sp_fad_122 = sp_fad_107 * sp_fad_106;
double sp_fad_123 = sp_fad_108 * sp_fad_106;
double sp_fad_124 = sp_fad_109 * sp_fad_106;
double sp_fad_125 = sp_fad_107 * sp_fad_107;
double sp_fad_126 = sp_fad_108 * sp_fad_107;
double sp_fad_127 = sp_fad_109 * sp_fad_107;
double sp_fad_128 = sp_fad_108 * sp_fad_108;
double sp_fad_129 = sp_fad_108 * sp_fad_109;
double sp_fad_130 = sp_fad_109 * sp_fad_109;
double sp_fad_131 = sp_fad_110 + sp_fad_57;
double sp_fad_132 = sp_fad_111 + sp_fad_58;
double sp_fad_133 = sp_fad_112 + sp_fad_59;
double sp_fad_134 = sp_fad_113 + sp_fad_60;
double sp_fad_135 = sp_fad_114 + sp_fad_61;
double sp_fad_136 = sp_fad_115 + sp_fad_62;
double sp_fad_137 = sp_fad_116 + sp_fad_63;
double sp_fad_138 = sp_fad_117 + sp_fad_64;
double sp_fad_139 = sp_fad_118 + sp_fad_65;
double sp_fad_140 = sp_fad_119 + sp_fad_66;
double sp_fad_141 = sp_fad_120 + sp_fad_67;
double sp_fad_142 = sp_fad_121 + sp_fad_68;
double sp_fad_143 = sp_fad_122 + sp_fad_69;
double sp_fad_144 = sp_fad_123 + sp_fad_70;
double sp_fad_145 = sp_fad_124 + sp_fad_71;
double sp_fad_146 = sp_fad_125 + sp_fad_72;
double sp_fad_147 = sp_fad_126 + sp_fad_73;
double sp_fad_148 = sp_fad_127 + sp_fad_74;
double sp_fad_149 = sp_fad_128 + sp_fad_75;
double sp_fad_150 = sp_fad_129 + sp_fad_76;
double sp_fad_151 = sp_fad_130 + sp_fad_77;
double sp_fad_152 = sp_fad_93 * sp_fad_42;
double sp_fad_153 = sp_fad_93 * sp_fad_39;
double sp_fad_154 = sp_fad_82 * sp_fad_42;
double sp_fad_155 = sp_fad_82 * sp_fad_28;
double sp_fad_156 = sp_fad_87 * sp_fad_28;
double sp_fad_157 = sp_fad_87 * sp_fad_39;
double sp_fad_158 = -sp_fad_156;
double sp_fad_159 = -sp_fad_155;
double sp_fad_160 = -sp_fad_157;
double sp_fad_161 = -sp_fad_153;
double sp_fad_162 = -sp_fad_152;
double sp_fad_163 = -sp_fad_154;
double sp_fad_164 = sp_fad_158 + sp_fad_152;
double sp_fad_165 = sp_fad_159 + sp_fad_153;
double sp_fad_166 = sp_fad_160 + sp_fad_154;
double sp_fad_167 = sp_fad_161 + sp_fad_155;
double sp_fad_168 = sp_fad_162 + sp_fad_156;
double sp_fad_169 = sp_fad_163 + sp_fad_157;
double sp_fad_170 = sp_fad_164 * sp_fad_164;
double sp_fad_171 = sp_fad_164 * sp_fad_165;
double sp_fad_172 = sp_fad_164 * sp_fad_166;
double sp_fad_173 = sp_fad_164 * sp_fad_167;
double sp_fad_174 = sp_fad_164 * sp_fad_168;
double sp_fad_175 = sp_fad_164 * sp_fad_169;
double sp_fad_176 = sp_fad_165 * sp_fad_165;
double sp_fad_177 = sp_fad_166 * sp_fad_165;
double sp_fad_178 = sp_fad_167 * sp_fad_165;
double sp_fad_179 = sp_fad_168 * sp_fad_165;
double sp_fad_180 = sp_fad_165 * sp_fad_169;
double sp_fad_181 = sp_fad_166 * sp_fad_166;
double sp_fad_182 = sp_fad_166 * sp_fad_167;
double sp_fad_183 = sp_fad_166 * sp_fad_168;
double sp_fad_184 = sp_fad_166 * sp_fad_169;
double sp_fad_185 = sp_fad_167 * sp_fad_167;
double sp_fad_186 = sp_fad_167 * sp_fad_168;
double sp_fad_187 = sp_fad_167 * sp_fad_169;
double sp_fad_188 = sp_fad_168 * sp_fad_168;
double sp_fad_189 = sp_fad_168 * sp_fad_169;
double sp_fad_190 = sp_fad_169 * sp_fad_169;
double sp_fad_191 = sp_fad_131 + sp_fad_170;
double sp_fad_192 = sp_fad_132 + sp_fad_171;
double sp_fad_193 = sp_fad_133 + sp_fad_172;
double sp_fad_194 = sp_fad_134 + sp_fad_173;
double sp_fad_195 = sp_fad_135 + sp_fad_174;
double sp_fad_196 = sp_fad_136 + sp_fad_175;
double sp_fad_197 = sp_fad_137 + sp_fad_176;
double sp_fad_198 = sp_fad_138 + sp_fad_177;
double sp_fad_199 = sp_fad_139 + sp_fad_178;
double sp_fad_200 = sp_fad_140 + sp_fad_179;
double sp_fad_201 = sp_fad_141 + sp_fad_180;
double sp_fad_202 = sp_fad_142 + sp_fad_181;
double sp_fad_203 = sp_fad_143 + sp_fad_182;
double sp_fad_204 = sp_fad_144 + sp_fad_183;
double sp_fad_205 = sp_fad_145 + sp_fad_184;
double sp_fad_206 = sp_fad_146 + sp_fad_185;
double sp_fad_207 = sp_fad_147 + sp_fad_186;
double sp_fad_208 = sp_fad_148 + sp_fad_187;
double sp_fad_209 = sp_fad_149 + sp_fad_188;
double sp_fad_210 = sp_fad_150 + sp_fad_189;
double sp_fad_211 = sp_fad_151 + sp_fad_190;
double sp_fad_212 = 795774.7154594767 * sp_fad_191;
double sp_fad_213 = 795774.7154594767 * sp_fad_192;
double sp_fad_214 = 795774.7154594767 * sp_fad_193;
double sp_fad_215 = 795774.7154594767 * sp_fad_194;
double sp_fad_216 = 795774.7154594767 * sp_fad_195;
double sp_fad_217 = 795774.7154594767 * sp_fad_196;
double sp_fad_218 = 795774.7154594767 * sp_fad_197;
double sp_fad_219 = 795774.7154594767 * sp_fad_198;
double sp_fad_220 = 795774.7154594767 * sp_fad_199;
double sp_fad_221 = 795774.7154594767 * sp_fad_200;
double sp_fad_222 = 795774.7154594767 * sp_fad_201;
double sp_fad_223 = 795774.7154594767 * sp_fad_202;
double sp_fad_224 = 795774.7154594767 * sp_fad_203;
double sp_fad_225 = 795774.7154594767 * sp_fad_204;
double sp_fad_226 = 795774.7154594767 * sp_fad_205;
double sp_fad_227 = 795774.7154594767 * sp_fad_206;
double sp_fad_228 = 795774.7154594767 * sp_fad_207;
double sp_fad_229 = 795774.7154594767 * sp_fad_208;
double sp_fad_230 = 795774.7154594767 * sp_fad_209;
double sp_fad_231 = 795774.7154594767 * sp_fad_210;
double sp_fad_232 = 795774.7154594767 * sp_fad_211;
double sp_fad_233 = sp_fad_28 * sp_fad_28;
double sp_fad_234 = sp_fad_28 * sp_fad_39;
double sp_fad_235 = sp_fad_42 * sp_fad_28;
double sp_fad_236 = sp_fad_39 * sp_fad_39;
double sp_fad_237 = sp_fad_42 * sp_fad_39;
double sp_fad_238 = sp_fad_42 * sp_fad_42;
double sp_fad_239 = sp_fad_93 * sp_fad_93;
double sp_fad_240 = sp_fad_93 * sp_fad_82;
double sp_fad_241 = sp_fad_93 * sp_fad_87;
double sp_fad_242 = sp_fad_82 * sp_fad_82;
double sp_fad_243 = sp_fad_82 * sp_fad_87;
double sp_fad_244 = sp_fad_87 * sp_fad_87;
double sp_fad_245 = sp_fad_239 + sp_fad_233;
double sp_fad_246 = sp_fad_240 + sp_fad_234;
double sp_fad_247 = sp_fad_241 + sp_fad_235;
double sp_fad_248 = sp_fad_242 + sp_fad_236;
double sp_fad_249 = sp_fad_243 + sp_fad_237;
double sp_fad_250 = sp_fad_238 + sp_fad_244;
double sp_fad_251 = sp_fad_35 * sp_fad_35;
double sp_fad_252 = sp_fad_35 * sp_fad_27;
double sp_fad_253 = sp_fad_22 * sp_fad_35;
double sp_fad_254 = sp_fad_27 * sp_fad_27;
double sp_fad_255 = sp_fad_22 * sp_fad_27;
double sp_fad_256 = sp_fad_22 * sp_fad_22;
double sp_fad_257 = sp_fad_245 + sp_fad_251;
double sp_fad_258 = sp_fad_246 + sp_fad_252;
double sp_fad_259 = sp_fad_247 + sp_fad_253;
double sp_fad_260 = sp_fad_248 + sp_fad_254;
double sp_fad_261 = sp_fad_249 + sp_fad_255;
double sp_fad_262 = sp_fad_250 + sp_fad_256;
double sp_fad_263 = 0.001 * sp_fad_257;
double sp_fad_264 = 0.001 * sp_fad_258;
double sp_fad_265 = 0.001 * sp_fad_259;
double sp_fad_266 = 0.001 * sp_fad_260;
double sp_fad_267 = 0.001 * sp_fad_261;
double sp_fad_268 = 0.001 * sp_fad_262;
double sp_fad_269 = fabs(sp_fad_21);
double sp_fad_270 = sp_fad_212 * sp_fad_269;
double sp_fad_271 = sp_fad_213 * sp_fad_269;
double sp_fad_272 = sp_fad_214 * sp_fad_269;
double sp_fad_273 = sp_fad_215 * sp_fad_269;
double sp_fad_274 = sp_fad_216 * sp_fad_269;
double sp_fad_275 = sp_fad_217 * sp_fad_269;
double sp_fad_276 = sp_fad_218 * sp_fad_269;
double sp_fad_277 = sp_fad_219 * sp_fad_269;
double sp_fad_278 = sp_fad_220 * sp_fad_269;
double sp_fad_279 = sp_fad_221 * sp_fad_269;
double sp_fad_280 = sp_fad_222 * sp_fad_269;
double sp_fad_281 = sp_fad_223 * sp_fad_269;
double sp_fad_282 = sp_fad_224 * sp_fad_269;
double sp_fad_283 = sp_fad_225 * sp_fad_269;
double sp_fad_284 = sp_fad_226 * sp_fad_269;
double sp_fad_285 = sp_fad_227 * sp_fad_269;
double sp_fad_286 = sp_fad_228 * sp_fad_269;
double sp_fad_287 = sp_fad_229 * sp_fad_269;
double sp_fad_288 = sp_fad_230 * sp_fad_269;
double sp_fad_289 = sp_fad_231 * sp_fad_269;
double sp_fad_290 = sp_fad_232 * sp_fad_269;
double sp_fad_291 = sp_fad_263 * sp_fad_269;
double sp_fad_292 = sp_fad_264 * sp_fad_269;
double sp_fad_293 = sp_fad_265 * sp_fad_269;
double sp_fad_294 = sp_fad_266 * sp_fad_269;
double sp_fad_295 = sp_fad_267 * sp_fad_269;
double sp_fad_296 = sp_fad_268 * sp_fad_269;
for (int iq = 0; iq < 4; ++iq)
{
  // ------------------------ 
  // Section: Intermediates
  // Inputs: 
  // Outputs: fw0, fw1, fw2, fw3, fw4, fw5, fw6, fw7, fw8, fw9, fw10, fw11, fw12, fw13, fw14, fw15, fw16, fw17, fw18, fw19, fw20, fw21, fw22, fw23, fw24, fw25, fw26
  double fw0 = 0;
  double fw1 = 0;
  double fw2 = 0;
  double fw3 = 0;
  double fw4 = 0;
  double fw5 = 0;
  double fw6 = 0;
  double fw7 = 0;
  double fw8 = 0;
  double fw9 = 0;
  double fw10 = 0;
  double fw11 = 0;
  double fw12 = 0;
  double fw13 = 0;
  double fw14 = 0;
  double fw15 = 0;
  double fw16 = 0;
  double fw17 = 0;
  double fw18 = 0;
  double fw19 = 0;
  double fw20 = 0;
  double fw21 = 0;
  double fw22 = 0;
  double fw23 = 0;
  double fw24 = 0;
  double fw25 = 0;
  double fw26 = 0;
  {
    fw0 = sp_fad_291 * weights_fad[iq];
    fw1 = sp_fad_292 * weights_fad[iq];
    fw2 = sp_fad_293 * weights_fad[iq];
    fw3 = sp_fad_276 * weights_fad[iq];
    fw4 = sp_fad_271 * weights_fad[iq];
    fw5 = sp_fad_278 * weights_fad[iq];
    fw6 = sp_fad_277 * weights_fad[iq];
    fw7 = sp_fad_279 * weights_fad[iq];
    fw8 = sp_fad_280 * weights_fad[iq];
    fw9 = sp_fad_270 * weights_fad[iq];
    fw10 = sp_fad_273 * weights_fad[iq];
    fw11 = sp_fad_272 * weights_fad[iq];
    fw12 = sp_fad_274 * weights_fad[iq];
    fw13 = sp_fad_275 * weights_fad[iq];
    fw14 = sp_fad_294 * weights_fad[iq];
    fw15 = sp_fad_295 * weights_fad[iq];
    fw16 = sp_fad_285 * weights_fad[iq];
    fw17 = sp_fad_282 * weights_fad[iq];
    fw18 = sp_fad_286 * weights_fad[iq];
    fw19 = sp_fad_287 * weights_fad[iq];
    fw20 = sp_fad_281 * weights_fad[iq];
    fw21 = sp_fad_283 * weights_fad[iq];
    fw22 = sp_fad_284 * weights_fad[iq];
    fw23 = sp_fad_296 * weights_fad[iq];
    fw24 = sp_fad_288 * weights_fad[iq];
    fw25 = sp_fad_289 * weights_fad[iq];
    fw26 = sp_fad_290 * weights_fad[iq];
  }
  // ------------------------ 
  // ------------------------ 
  // Section: Tensor Computation
  // Inputs: fw8, FE2_C1_Qfad, fw26, fw25, fw1, FE2_C0_Qfad, fw20, FE2_C2_D010_Qfad, fw22, fw17, fw21, fw6, fw2, FE2_C0_D001_Qfad, fw7, fw18, fw4, fw24, FE2_C2_Qfad, fw16, fw0, fw3, fw14, fw12, fw5, fw15, fw9, FE2_C0_D010_Qfad, FE2_C2_D100_Qfad, fw10, fw11, fw13, FE2_C1_D001_Qfad, fw23, fw19, FE2_C1_D100_Qfad
  // Outputs: A
  {
    double temp_0[6] = {0};
    for (int j = 0; j < 6; ++j)
    {
      temp_0[j] = fw0 * FE2_C0_Qfad[0][0][iq][j];
    }
    double temp_1[6] = {0};
    for (int j = 0; j < 6; ++j)
    {
      temp_1[j] = fw1 * FE2_C1_Qfad[0][0][iq][j];
    }
    double temp_2[6] = {0};
    for (int j = 0; j < 6; ++j)
    {
      temp_2[j] = fw2 * FE2_C2_Qfad[0][0][iq][j];
    }
    double temp_3[6] = {0};
    for (int j = 0; j < 6; ++j)
    {
      temp_3[j] = fw3 * FE2_C0_D010_Qfad[0][0][0][j];
    }
    double temp_4[6] = {0};
    for (int j = 0; j < 6; ++j)
    {
      temp_4[j] = fw4 * FE2_C0_D001_Qfad[0][0][0][j];
    }
    double temp_5[6] = {0};
    for (int j = 0; j < 6; ++j)
    {
      temp_5[j] = fw5 * FE2_C1_D100_Qfad[0][0][0][j];
    }
    double temp_6[6] = {0};
    for (int j = 0; j < 6; ++j)
    {
      temp_6[j] = fw6 * FE2_C1_D001_Qfad[0][0][0][j];
    }
    double temp_7[6] = {0};
    for (int j = 0; j < 6; ++j)
    {
      temp_7[j] = fw7 * FE2_C2_D100_Qfad[0][0][0][j];
    }
    double temp_8[6] = {0};
    for (int j = 0; j < 6; ++j)
    {
      temp_8[j] = fw8 * FE2_C2_D010_Qfad[0][0][0][j];
    }
    double temp_9[6] = {0};
    for (int j = 0; j < 6; ++j)
    {
      temp_9[j] = fw4 * FE2_C0_D010_Qfad[0][0][0][j];
    }
    double temp_10[6] = {0};
    for (int j = 0; j < 6; ++j)
    {
      temp_10[j] = fw9 * FE2_C0_D001_Qfad[0][0][0][j];
    }
    double temp_11[6] = {0};
    for (int j = 0; j < 6; ++j)
    {
      temp_11[j] = fw10 * FE2_C1_D100_Qfad[0][0][0][j];
    }
    double temp_12[6] = {0};
    for (int j = 0; j < 6; ++j)
    {
      temp_12[j] = fw11 * FE2_C1_D001_Qfad[0][0][0][j];
    }
    double temp_13[6] = {0};
    for (int j = 0; j < 6; ++j)
    {
      temp_13[j] = fw12 * FE2_C2_D100_Qfad[0][0][0][j];
    }
    double temp_14[6] = {0};
    for (int j = 0; j < 6; ++j)
    {
      temp_14[j] = fw13 * FE2_C2_D010_Qfad[0][0][0][j];
    }
    double temp_15[6] = {0};
    for (int j = 0; j < 6; ++j)
    {
      temp_15[j] = fw1 * FE2_C0_Qfad[0][0][iq][j];
    }
    double temp_16[6] = {0};
    for (int j = 0; j < 6; ++j)
    {
      temp_16[j] = fw14 * FE2_C1_Qfad[0][0][iq][j];
    }
    double temp_17[6] = {0};
    for (int j = 0; j < 6; ++j)
    {
      temp_17[j] = fw15 * FE2_C2_Qfad[0][0][iq][j];
    }
    double temp_18[6] = {0};
    for (int j = 0; j < 6; ++j)
    {
      temp_18[j] = fw5 * FE2_C0_D010_Qfad[0][0][0][j];
    }
    double temp_19[6] = {0};
    for (int j = 0; j < 6; ++j)
    {
      temp_19[j] = fw10 * FE2_C0_D001_Qfad[0][0][0][j];
    }
    double temp_20[6] = {0};
    for (int j = 0; j < 6; ++j)
    {
      temp_20[j] = fw16 * FE2_C1_D100_Qfad[0][0][0][j];
    }
    double temp_21[6] = {0};
    for (int j = 0; j < 6; ++j)
    {
      temp_21[j] = fw17 * FE2_C1_D001_Qfad[0][0][0][j];
    }
    double temp_22[6] = {0};
    for (int j = 0; j < 6; ++j)
    {
      temp_22[j] = fw18 * FE2_C2_D100_Qfad[0][0][0][j];
    }
    double temp_23[6] = {0};
    for (int j = 0; j < 6; ++j)
    {
      temp_23[j] = fw19 * FE2_C2_D010_Qfad[0][0][0][j];
    }
    double temp_24[6] = {0};
    for (int j = 0; j < 6; ++j)
    {
      temp_24[j] = fw6 * FE2_C0_D010_Qfad[0][0][0][j];
    }
    double temp_25[6] = {0};
    for (int j = 0; j < 6; ++j)
    {
      temp_25[j] = fw11 * FE2_C0_D001_Qfad[0][0][0][j];
    }
    double temp_26[6] = {0};
    for (int j = 0; j < 6; ++j)
    {
      temp_26[j] = fw17 * FE2_C1_D100_Qfad[0][0][0][j];
    }
    double temp_27[6] = {0};
    for (int j = 0; j < 6; ++j)
    {
      temp_27[j] = fw20 * FE2_C1_D001_Qfad[0][0][0][j];
    }
    double temp_28[6] = {0};
    for (int j = 0; j < 6; ++j)
    {
      temp_28[j] = fw21 * FE2_C2_D100_Qfad[0][0][0][j];
    }
    double temp_29[6] = {0};
    for (int j = 0; j < 6; ++j)
    {
      temp_29[j] = fw22 * FE2_C2_D010_Qfad[0][0][0][j];
    }
    double temp_30[6] = {0};
    for (int j = 0; j < 6; ++j)
    {
      temp_30[j] = fw2 * FE2_C0_Qfad[0][0][iq][j];
    }
    double temp_31[6] = {0};
    for (int j = 0; j < 6; ++j)
    {
      temp_31[j] = fw15 * FE2_C1_Qfad[0][0][iq][j];
    }
    double temp_32[6] = {0};
    for (int j = 0; j < 6; ++j)
    {
      temp_32[j] = fw23 * FE2_C2_Qfad[0][0][iq][j];
    }
    double temp_33[6] = {0};
    for (int j = 0; j < 6; ++j)
    {
      temp_33[j] = fw7 * FE2_C0_D010_Qfad[0][0][0][j];
    }
    double temp_34[6] = {0};
    for (int j = 0; j < 6; ++j)
    {
      temp_34[j] = fw12 * FE2_C0_D001_Qfad[0][0][0][j];
    }
    double temp_35[6] = {0};
    for (int j = 0; j < 6; ++j)
    {
      temp_35[j] = fw18 * FE2_C1_D100_Qfad[0][0][0][j];
    }
    double temp_36[6] = {0};
    for (int j = 0; j < 6; ++j)
    {
      temp_36[j] = fw21 * FE2_C1_D001_Qfad[0][0][0][j];
    }
    double temp_37[6] = {0};
    for (int j = 0; j < 6; ++j)
    {
      temp_37[j] = fw24 * FE2_C2_D100_Qfad[0][0][0][j];
    }
    double temp_38[6] = {0};
    for (int j = 0; j < 6; ++j)
    {
      temp_38[j] = fw25 * FE2_C2_D010_Qfad[0][0][0][j];
    }
    double temp_39[6] = {0};
    for (int j = 0; j < 6; ++j)
    {
      temp_39[j] = fw8 * FE2_C0_D010_Qfad[0][0][0][j];
    }
    double temp_40[6] = {0};
    for (int j = 0; j < 6; ++j)
    {
      temp_40[j] = fw13 * FE2_C0_D001_Qfad[0][0][0][j];
    }
    double temp_41[6] = {0};
    for (int j = 0; j < 6; ++j)
    {
      temp_41[j] = fw19 * FE2_C1_D100_Qfad[0][0][0][j];
    }
    double temp_42[6] = {0};
    for (int j = 0; j < 6; ++j)
    {
      temp_42[j] = fw22 * FE2_C1_D001_Qfad[0][0][0][j];
    }
    double temp_43[6] = {0};
    for (int j = 0; j < 6; ++j)
    {
      temp_43[j] = fw25 * FE2_C2_D100_Qfad[0][0][0][j];
    }
    double temp_44[6] = {0};
    for (int j = 0; j < 6; ++j)
    {
      temp_44[j] = fw26 * FE2_C2_D010_Qfad[0][0][0][j];
    }
    for (int j = 0; j < 6; ++j)
    {
      for (int i = 0; i < 6; ++i)
      {
        A[6 * (i) + (j)] += FE2_C0_Qfad[0][0][iq][i] * temp_0[j];
        A[6 * (i) + (j)] += FE2_C0_Qfad[0][0][iq][i] * temp_1[j];
        A[6 * (i) + (j)] += FE2_C0_Qfad[0][0][iq][i] * temp_2[j];
        A[6 * (i) + (j)] += FE2_C0_D010_Qfad[0][0][0][i] * temp_3[j];
        A[6 * (i) + (j)] += FE2_C0_D010_Qfad[0][0][0][i] * temp_4[j];
        A[6 * (i) + (j)] += FE2_C0_D010_Qfad[0][0][0][i] * temp_5[j];
        A[6 * (i) + (j)] += FE2_C0_D010_Qfad[0][0][0][i] * temp_6[j];
        A[6 * (i) + (j)] += FE2_C0_D010_Qfad[0][0][0][i] * temp_7[j];
        A[6 * (i) + (j)] += FE2_C0_D010_Qfad[0][0][0][i] * temp_8[j];
        A[6 * (i) + (j)] += FE2_C0_D001_Qfad[0][0][0][i] * temp_9[j];
        A[6 * (i) + (j)] += FE2_C0_D001_Qfad[0][0][0][i] * temp_10[j];
        A[6 * (i) + (j)] += FE2_C0_D001_Qfad[0][0][0][i] * temp_11[j];
        A[6 * (i) + (j)] += FE2_C0_D001_Qfad[0][0][0][i] * temp_12[j];
        A[6 * (i) + (j)] += FE2_C0_D001_Qfad[0][0][0][i] * temp_13[j];
        A[6 * (i) + (j)] += FE2_C0_D001_Qfad[0][0][0][i] * temp_14[j];
        A[6 * (i) + (j)] += FE2_C1_Qfad[0][0][iq][i] * temp_15[j];
        A[6 * (i) + (j)] += FE2_C1_Qfad[0][0][iq][i] * temp_16[j];
        A[6 * (i) + (j)] += FE2_C1_Qfad[0][0][iq][i] * temp_17[j];
        A[6 * (i) + (j)] += FE2_C1_D100_Qfad[0][0][0][i] * temp_18[j];
        A[6 * (i) + (j)] += FE2_C1_D100_Qfad[0][0][0][i] * temp_19[j];
        A[6 * (i) + (j)] += FE2_C1_D100_Qfad[0][0][0][i] * temp_20[j];
        A[6 * (i) + (j)] += FE2_C1_D100_Qfad[0][0][0][i] * temp_21[j];
        A[6 * (i) + (j)] += FE2_C1_D100_Qfad[0][0][0][i] * temp_22[j];
        A[6 * (i) + (j)] += FE2_C1_D100_Qfad[0][0][0][i] * temp_23[j];
        A[6 * (i) + (j)] += FE2_C1_D001_Qfad[0][0][0][i] * temp_24[j];
        A[6 * (i) + (j)] += FE2_C1_D001_Qfad[0][0][0][i] * temp_25[j];
        A[6 * (i) + (j)] += FE2_C1_D001_Qfad[0][0][0][i] * temp_26[j];
        A[6 * (i) + (j)] += FE2_C1_D001_Qfad[0][0][0][i] * temp_27[j];
        A[6 * (i) + (j)] += FE2_C1_D001_Qfad[0][0][0][i] * temp_28[j];
        A[6 * (i) + (j)] += FE2_C1_D001_Qfad[0][0][0][i] * temp_29[j];
        A[6 * (i) + (j)] += FE2_C2_Qfad[0][0][iq][i] * temp_30[j];
        A[6 * (i) + (j)] += FE2_C2_Qfad[0][0][iq][i] * temp_31[j];
        A[6 * (i) + (j)] += FE2_C2_Qfad[0][0][iq][i] * temp_32[j];
        A[6 * (i) + (j)] += FE2_C2_D100_Qfad[0][0][0][i] * temp_33[j];
        A[6 * (i) + (j)] += FE2_C2_D100_Qfad[0][0][0][i] * temp_34[j];
        A[6 * (i) + (j)] += FE2_C2_D100_Qfad[0][0][0][i] * temp_35[j];
        A[6 * (i) + (j)] += FE2_C2_D100_Qfad[0][0][0][i] * temp_36[j];
        A[6 * (i) + (j)] += FE2_C2_D100_Qfad[0][0][0][i] * temp_37[j];
        A[6 * (i) + (j)] += FE2_C2_D100_Qfad[0][0][0][i] * temp_38[j];
        A[6 * (i) + (j)] += FE2_C2_D010_Qfad[0][0][0][i] * temp_39[j];
        A[6 * (i) + (j)] += FE2_C2_D010_Qfad[0][0][0][i] * temp_40[j];
        A[6 * (i) + (j)] += FE2_C2_D010_Qfad[0][0][0][i] * temp_41[j];
        A[6 * (i) + (j)] += FE2_C2_D010_Qfad[0][0][0][i] * temp_42[j];
        A[6 * (i) + (j)] += FE2_C2_D010_Qfad[0][0][0][i] * temp_43[j];
        A[6 * (i) + (j)] += FE2_C2_D010_Qfad[0][0][0][i] * temp_44[j];
      }
    }
  }
  // ------------------------ 
}

}



ufcx_integral integral_b9d745df7c51ad241ad2646bcd287b24a7aa65fe_tetrahedron =
{
  .enabled_coefficients = NULL,
  .tabulate_tensor_float32 = NULL,
  .tabulate_tensor_float64 = tabulate_tensor_integral_b9d745df7c51ad241ad2646bcd287b24a7aa65fe_tetrahedron,
  .tabulate_tensor_complex64 = NULL,
  .tabulate_tensor_complex128 = NULL,
  .needs_facet_permutations = false,
  .coordinate_element_hash = UINT64_C(16933917894078122104),
  .domain = 3,
};

// End of code for integral integral_b9d745df7c51ad241ad2646bcd287b24a7aa65fe_tetrahedron

// Code for form form_ebb8212fe44eef0a19d8e97181b23619c204a711


uint64_t finite_element_hashes_form_ebb8212fe44eef0a19d8e97181b23619c204a711[2] = {UINT64_C(16913352536932768155), UINT64_C(16913352536932768155)};
int form_integral_offsets_form_ebb8212fe44eef0a19d8e97181b23619c204a711[6] = {0, 1, 1, 1, 1, 1};
static ufcx_integral* form_integrals_form_ebb8212fe44eef0a19d8e97181b23619c204a711[1] = {&integral_b9d745df7c51ad241ad2646bcd287b24a7aa65fe_tetrahedron};
int form_integral_ids_form_ebb8212fe44eef0a19d8e97181b23619c204a711[1] = {-1};






ufcx_form form_ebb8212fe44eef0a19d8e97181b23619c204a711 =
{

  .signature = "30b3931803701916437de647ca0494d2d077da4d2ca4e68049c0924022084810527750268ede28bf131e453316942b234820341404e244b41c4a3719e650f6d8",
  .rank = 2,

  .num_coefficients = 0,
  .original_coefficient_positions = NULL,
  .coefficient_name_map = NULL,

  .num_constants = 0,
  .constant_ranks = NULL,
  .constant_shapes = NULL,
  .constant_name_map = NULL,

  .finite_element_hashes = finite_element_hashes_form_ebb8212fe44eef0a19d8e97181b23619c204a711,

  .form_integrals = form_integrals_form_ebb8212fe44eef0a19d8e97181b23619c204a711,
  .form_integral_ids = form_integral_ids_form_ebb8212fe44eef0a19d8e97181b23619c204a711,
  .form_integral_offsets = form_integral_offsets_form_ebb8212fe44eef0a19d8e97181b23619c204a711
};

// Alias name
ufcx_form* form_libffcx_forms_40f35f4ecdec5fd54e2f5a545a176662957fa58f_0 = &form_ebb8212fe44eef0a19d8e97181b23619c204a711;

// End of code for form form_ebb8212fe44eef0a19d8e97181b23619c204a711


/************************************************************/

static void *_cffi_types[] = {
/*  0 */ _CFFI_OP(_CFFI_OP_FUNCTION, 60), // void()(_cffi_double_complex_t *, _cffi_double_complex_t const *, _cffi_double_complex_t const *, double const *, int const *, uint8_t const *, void *)
/*  1 */ _CFFI_OP(_CFFI_OP_POINTER, 38), // _cffi_double_complex_t *
/*  2 */ _CFFI_OP(_CFFI_OP_POINTER, 38), // _cffi_double_complex_t const *
/*  3 */ _CFFI_OP(_CFFI_OP_NOOP, 2),
/*  4 */ _CFFI_OP(_CFFI_OP_POINTER, 43), // double const *
/*  5 */ _CFFI_OP(_CFFI_OP_POINTER, 47), // int const *
/*  6 */ _CFFI_OP(_CFFI_OP_POINTER, 55), // uint8_t const *
/*  7 */ _CFFI_OP(_CFFI_OP_POINTER, 60), // void *
/*  8 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  9 */ _CFFI_OP(_CFFI_OP_FUNCTION, 60), // void()(_cffi_float_complex_t *, _cffi_float_complex_t const *, _cffi_float_complex_t const *, float const *, int const *, uint8_t const *, void *)
/* 10 */ _CFFI_OP(_CFFI_OP_POINTER, 39), // _cffi_float_complex_t *
/* 11 */ _CFFI_OP(_CFFI_OP_POINTER, 39), // _cffi_float_complex_t const *
/* 12 */ _CFFI_OP(_CFFI_OP_NOOP, 11),
/* 13 */ _CFFI_OP(_CFFI_OP_POINTER, 44), // float const *
/* 14 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 15 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 16 */ _CFFI_OP(_CFFI_OP_NOOP, 7),
/* 17 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 18 */ _CFFI_OP(_CFFI_OP_FUNCTION, 60), // void()(double *, double const *, double const *, double const *, int const *, uint8_t const *, void *)
/* 19 */ _CFFI_OP(_CFFI_OP_POINTER, 43), // double *
/* 20 */ _CFFI_OP(_CFFI_OP_NOOP, 4),
/* 21 */ _CFFI_OP(_CFFI_OP_NOOP, 4),
/* 22 */ _CFFI_OP(_CFFI_OP_NOOP, 4),
/* 23 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 24 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 25 */ _CFFI_OP(_CFFI_OP_NOOP, 7),
/* 26 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 27 */ _CFFI_OP(_CFFI_OP_FUNCTION, 60), // void()(float *, float const *, float const *, float const *, int const *, uint8_t const *, void *)
/* 28 */ _CFFI_OP(_CFFI_OP_POINTER, 44), // float *
/* 29 */ _CFFI_OP(_CFFI_OP_NOOP, 13),
/* 30 */ _CFFI_OP(_CFFI_OP_NOOP, 13),
/* 31 */ _CFFI_OP(_CFFI_OP_NOOP, 13),
/* 32 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 33 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 34 */ _CFFI_OP(_CFFI_OP_NOOP, 7),
/* 35 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 36 */ _CFFI_OP(_CFFI_OP_POINTER, 37), // _Bool const *
/* 37 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 1), // _Bool
/* 38 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 49), // _cffi_double_complex_t
/* 39 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 48), // _cffi_float_complex_t
/* 40 */ _CFFI_OP(_CFFI_OP_POINTER, 41), // char const * *
/* 41 */ _CFFI_OP(_CFFI_OP_POINTER, 42), // char const *
/* 42 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 2), // char
/* 43 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14), // double
/* 44 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 13), // float
/* 45 */ _CFFI_OP(_CFFI_OP_POINTER, 47), // int *
/* 46 */ _CFFI_OP(_CFFI_OP_POINTER, 5), // int const * *
/* 47 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7), // int
/* 48 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 0), // ufcx_form
/* 49 */ _CFFI_OP(_CFFI_OP_POINTER, 50), // ufcx_integral * *
/* 50 */ _CFFI_OP(_CFFI_OP_POINTER, 51), // ufcx_integral *
/* 51 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 1), // ufcx_integral
/* 52 */ _CFFI_OP(_CFFI_OP_ENUM, 0), // ufcx_integral_type
/* 53 */ _CFFI_OP(_CFFI_OP_POINTER, 54), // uint64_t *
/* 54 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 24), // uint64_t
/* 55 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 18), // uint8_t
/* 56 */ _CFFI_OP(_CFFI_OP_POINTER, 0), // void(*)(_cffi_double_complex_t *, _cffi_double_complex_t const *, _cffi_double_complex_t const *, double const *, int const *, uint8_t const *, void *)
/* 57 */ _CFFI_OP(_CFFI_OP_POINTER, 9), // void(*)(_cffi_float_complex_t *, _cffi_float_complex_t const *, _cffi_float_complex_t const *, float const *, int const *, uint8_t const *, void *)
/* 58 */ _CFFI_OP(_CFFI_OP_POINTER, 18), // void(*)(double *, double const *, double const *, double const *, int const *, uint8_t const *, void *)
/* 59 */ _CFFI_OP(_CFFI_OP_POINTER, 27), // void(*)(float *, float const *, float const *, float const *, int const *, uint8_t const *, void *)
/* 60 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 0), // void
};

static int _cffi_const_cell(unsigned long long *o)
{
  int n = (cell) <= 0;
  *o = (unsigned long long)((cell) | 0);  /* check that cell is an integer */
  return n;
}

static int _cffi_const_exterior_facet(unsigned long long *o)
{
  int n = (exterior_facet) <= 0;
  *o = (unsigned long long)((exterior_facet) | 0);  /* check that exterior_facet is an integer */
  return n;
}

static int _cffi_const_interior_facet(unsigned long long *o)
{
  int n = (interior_facet) <= 0;
  *o = (unsigned long long)((interior_facet) | 0);  /* check that interior_facet is an integer */
  return n;
}

static int _cffi_const_vertex(unsigned long long *o)
{
  int n = (vertex) <= 0;
  *o = (unsigned long long)((vertex) | 0);  /* check that vertex is an integer */
  return n;
}

static int _cffi_const_ridge(unsigned long long *o)
{
  int n = (ridge) <= 0;
  *o = (unsigned long long)((ridge) | 0);  /* check that ridge is an integer */
  return n;
}

_CFFI_UNUSED_FN
static void _cffi_checkfld__ufcx_form(ufcx_form *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { char const * *tmp = &p->signature; (void)tmp; }
  (void)((p->rank) | 0);  /* check that 'ufcx_form.rank' is an integer */
  (void)((p->num_coefficients) | 0);  /* check that 'ufcx_form.num_coefficients' is an integer */
  { int * *tmp = &p->original_coefficient_positions; (void)tmp; }
  { char const * * *tmp = &p->coefficient_name_map; (void)tmp; }
  (void)((p->num_constants) | 0);  /* check that 'ufcx_form.num_constants' is an integer */
  { int const * *tmp = &p->constant_ranks; (void)tmp; }
  { int const * * *tmp = &p->constant_shapes; (void)tmp; }
  { char const * * *tmp = &p->constant_name_map; (void)tmp; }
  { uint64_t * *tmp = &p->finite_element_hashes; (void)tmp; }
  { ufcx_integral * * *tmp = &p->form_integrals; (void)tmp; }
  { int * *tmp = &p->form_integral_ids; (void)tmp; }
  { int * *tmp = &p->form_integral_offsets; (void)tmp; }
}
struct _cffi_align__ufcx_form { char x; ufcx_form y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld__ufcx_integral(ufcx_integral *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { _Bool const * *tmp = &p->enabled_coefficients; (void)tmp; }
  { void(* *tmp)(float *, float const *, float const *, float const *, int const *, uint8_t const *, void *) = &p->tabulate_tensor_float32; (void)tmp; }
  { void(* *tmp)(double *, double const *, double const *, double const *, int const *, uint8_t const *, void *) = &p->tabulate_tensor_float64; (void)tmp; }
  { void(* *tmp)(_cffi_float_complex_t *, _cffi_float_complex_t const *, _cffi_float_complex_t const *, float const *, int const *, uint8_t const *, void *) = &p->tabulate_tensor_complex64; (void)tmp; }
  { void(* *tmp)(_cffi_double_complex_t *, _cffi_double_complex_t const *, _cffi_double_complex_t const *, double const *, int const *, uint8_t const *, void *) = &p->tabulate_tensor_complex128; (void)tmp; }
  (void)((p->needs_facet_permutations) | 0);  /* check that 'ufcx_integral.needs_facet_permutations' is an integer */
  (void)((p->coordinate_element_hash) | 0);  /* check that 'ufcx_integral.coordinate_element_hash' is an integer */
  (void)((p->domain) | 0);  /* check that 'ufcx_integral.domain' is an integer */
}
struct _cffi_align__ufcx_integral { char x; ufcx_integral y; };

static ufcx_form *_cffi_var_form_ebb8212fe44eef0a19d8e97181b23619c204a711(void)
{
  return &(form_ebb8212fe44eef0a19d8e97181b23619c204a711);
}

static const struct _cffi_global_s _cffi_globals[] = {
  { "cell", (void *)_cffi_const_cell, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "exterior_facet", (void *)_cffi_const_exterior_facet, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "form_ebb8212fe44eef0a19d8e97181b23619c204a711", (void *)_cffi_var_form_ebb8212fe44eef0a19d8e97181b23619c204a711, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 48), (void *)0 },
  { "interior_facet", (void *)_cffi_const_interior_facet, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "ridge", (void *)_cffi_const_ridge, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "vertex", (void *)_cffi_const_vertex, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
};

static const struct _cffi_field_s _cffi_fields[] = {
  { "signature", offsetof(ufcx_form, signature),
                 sizeof(((ufcx_form *)0)->signature),
                 _CFFI_OP(_CFFI_OP_NOOP, 41) },
  { "rank", offsetof(ufcx_form, rank),
            sizeof(((ufcx_form *)0)->rank),
            _CFFI_OP(_CFFI_OP_NOOP, 47) },
  { "num_coefficients", offsetof(ufcx_form, num_coefficients),
                        sizeof(((ufcx_form *)0)->num_coefficients),
                        _CFFI_OP(_CFFI_OP_NOOP, 47) },
  { "original_coefficient_positions", offsetof(ufcx_form, original_coefficient_positions),
                                      sizeof(((ufcx_form *)0)->original_coefficient_positions),
                                      _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "coefficient_name_map", offsetof(ufcx_form, coefficient_name_map),
                            sizeof(((ufcx_form *)0)->coefficient_name_map),
                            _CFFI_OP(_CFFI_OP_NOOP, 40) },
  { "num_constants", offsetof(ufcx_form, num_constants),
                     sizeof(((ufcx_form *)0)->num_constants),
                     _CFFI_OP(_CFFI_OP_NOOP, 47) },
  { "constant_ranks", offsetof(ufcx_form, constant_ranks),
                      sizeof(((ufcx_form *)0)->constant_ranks),
                      _CFFI_OP(_CFFI_OP_NOOP, 5) },
  { "constant_shapes", offsetof(ufcx_form, constant_shapes),
                       sizeof(((ufcx_form *)0)->constant_shapes),
                       _CFFI_OP(_CFFI_OP_NOOP, 46) },
  { "constant_name_map", offsetof(ufcx_form, constant_name_map),
                         sizeof(((ufcx_form *)0)->constant_name_map),
                         _CFFI_OP(_CFFI_OP_NOOP, 40) },
  { "finite_element_hashes", offsetof(ufcx_form, finite_element_hashes),
                             sizeof(((ufcx_form *)0)->finite_element_hashes),
                             _CFFI_OP(_CFFI_OP_NOOP, 53) },
  { "form_integrals", offsetof(ufcx_form, form_integrals),
                      sizeof(((ufcx_form *)0)->form_integrals),
                      _CFFI_OP(_CFFI_OP_NOOP, 49) },
  { "form_integral_ids", offsetof(ufcx_form, form_integral_ids),
                         sizeof(((ufcx_form *)0)->form_integral_ids),
                         _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "form_integral_offsets", offsetof(ufcx_form, form_integral_offsets),
                             sizeof(((ufcx_form *)0)->form_integral_offsets),
                             _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "enabled_coefficients", offsetof(ufcx_integral, enabled_coefficients),
                            sizeof(((ufcx_integral *)0)->enabled_coefficients),
                            _CFFI_OP(_CFFI_OP_NOOP, 36) },
  { "tabulate_tensor_float32", offsetof(ufcx_integral, tabulate_tensor_float32),
                               sizeof(((ufcx_integral *)0)->tabulate_tensor_float32),
                               _CFFI_OP(_CFFI_OP_NOOP, 59) },
  { "tabulate_tensor_float64", offsetof(ufcx_integral, tabulate_tensor_float64),
                               sizeof(((ufcx_integral *)0)->tabulate_tensor_float64),
                               _CFFI_OP(_CFFI_OP_NOOP, 58) },
  { "tabulate_tensor_complex64", offsetof(ufcx_integral, tabulate_tensor_complex64),
                                 sizeof(((ufcx_integral *)0)->tabulate_tensor_complex64),
                                 _CFFI_OP(_CFFI_OP_NOOP, 57) },
  { "tabulate_tensor_complex128", offsetof(ufcx_integral, tabulate_tensor_complex128),
                                  sizeof(((ufcx_integral *)0)->tabulate_tensor_complex128),
                                  _CFFI_OP(_CFFI_OP_NOOP, 56) },
  { "needs_facet_permutations", offsetof(ufcx_integral, needs_facet_permutations),
                                sizeof(((ufcx_integral *)0)->needs_facet_permutations),
                                _CFFI_OP(_CFFI_OP_NOOP, 37) },
  { "coordinate_element_hash", offsetof(ufcx_integral, coordinate_element_hash),
                               sizeof(((ufcx_integral *)0)->coordinate_element_hash),
                               _CFFI_OP(_CFFI_OP_NOOP, 54) },
  { "domain", offsetof(ufcx_integral, domain),
              sizeof(((ufcx_integral *)0)->domain),
              _CFFI_OP(_CFFI_OP_NOOP, 55) },
};

static const struct _cffi_struct_union_s _cffi_struct_unions[] = {
  { "ufcx_form", 48, _CFFI_F_CHECK_FIELDS,
    sizeof(ufcx_form), offsetof(struct _cffi_align__ufcx_form, y), 0, 13 },
  { "ufcx_integral", 51, _CFFI_F_CHECK_FIELDS,
    sizeof(ufcx_integral), offsetof(struct _cffi_align__ufcx_integral, y), 13, 8 },
};

static const struct _cffi_enum_s _cffi_enums[] = {
  { "$ufcx_integral_type", 52, _cffi_prim_int(sizeof(ufcx_integral_type), ((ufcx_integral_type)-1) <= 0),
    "cell,exterior_facet,interior_facet,vertex,ridge" },
};

static const struct _cffi_typename_s _cffi_typenames[] = {
  { "ufcx_form", 48 },
  { "ufcx_integral", 51 },
  { "ufcx_integral_type", 52 },
  { "ufcx_tabulate_tensor_complex128", 0 },
  { "ufcx_tabulate_tensor_complex64", 9 },
  { "ufcx_tabulate_tensor_float32", 27 },
  { "ufcx_tabulate_tensor_float64", 18 },
};

static const struct _cffi_type_context_s _cffi_type_context = {
  _cffi_types,
  _cffi_globals,
  _cffi_fields,
  _cffi_struct_unions,
  _cffi_enums,
  _cffi_typenames,
  6,  /* num_globals */
  2,  /* num_struct_unions */
  1,  /* num_enums */
  7,  /* num_typenames */
  NULL,  /* no includes */
  61,  /* num_types */
  0,  /* flags */
};

#ifdef __GNUC__
#  pragma GCC visibility push(default)  /* for -fvisibility= */
#endif

#ifdef PYPY_VERSION
PyMODINIT_FUNC
_cffi_pypyinit_libffcx_forms_40f35f4ecdec5fd54e2f5a545a176662957fa58f(const void *p[])
{
    p[0] = (const void *)0x2601;
    p[1] = &_cffi_type_context;
#if PY_MAJOR_VERSION >= 3
    return NULL;
#endif
}
#  ifdef _MSC_VER
     PyMODINIT_FUNC
#  if PY_MAJOR_VERSION >= 3
     PyInit_libffcx_forms_40f35f4ecdec5fd54e2f5a545a176662957fa58f(void) { return NULL; }
#  else
     initlibffcx_forms_40f35f4ecdec5fd54e2f5a545a176662957fa58f(void) { }
#  endif
#  endif
#elif PY_MAJOR_VERSION >= 3
PyMODINIT_FUNC
PyInit_libffcx_forms_40f35f4ecdec5fd54e2f5a545a176662957fa58f(void)
{
  return _cffi_init("libffcx_forms_40f35f4ecdec5fd54e2f5a545a176662957fa58f", 0x2601, &_cffi_type_context);
}
#else
PyMODINIT_FUNC
initlibffcx_forms_40f35f4ecdec5fd54e2f5a545a176662957fa58f(void)
{
  _cffi_init("libffcx_forms_40f35f4ecdec5fd54e2f5a545a176662957fa58f", 0x2601, &_cffi_type_context);
}
#endif

#ifdef __GNUC__
#  pragma GCC visibility pop
#endif
